### ISSUE TITLE
How can we smooth the 3D object from stl file ?

### ISSUE THREAD

**Issue by ybdesire** [mikedh/trimesh#102]
Which function should I choose to smooth the triangulated mesh object ?

**Comment by mikedh** [comment]
Hey, trimesh doesn't have any actual smoothing implemented. `mesh.smoothed()` will return a version of the mesh where vertices at sharp corners are unmerged, so that if passed to opengl it will smooth shade curved surfaces (the `mesh.show()` call is using this version by default.) 

If you want actual smoothing, lapacian smoothing probably wouldn't be too hard to implement:
http://www.pmp-book.org/download/slides/Smoothing.pdf

**Comment by ybdesire** [comment]
@mikedh , Thanks a lot. Laplace smoothing works.

**Comment by mikedh** [comment]
Nice! If you have an implementation you'd be willing to share I'd be happy to look into including it in trimesh. 

Thanks!
Mike
