### ISSUE TITLE
consistent "direction" of an edge traversal?

### ISSUE THREAD

**Issue by DustinReagan** [mikedh/trimesh#1036]
I wrote the following code, which finds the 'border' edges of a non-watertight mesh:

```
mesh = trimesh.load_mesh(filepath)

# find the edges shared by only 1 face
edge_indices = mesh.faces_unique_edges.flatten()
counts = np.bincount(edge_indices)
unshared_edge_indices = np.where(counts == 1)
unshared_edges = mesh.edges_unique[unshared_edge_indices]

 # TODO: figure out the winding of the edge traversal
traversal = np.flip(trimesh.graph.traversals(unshared_edges, mode='dfs')[0])
```

This works fine, but the "direction" of the traversal seems to vary from mesh to mesh.  I also have code (not shown) that extrudes the border edge-loop in the direction of the best-fit plane's normal.  If the direction of the traversal goes one way, my extruded triangles are oriented correctly, however if the direction of the traversal is opposite, the extruded triangles are 'inside out'.  

Questions:

1) Is there a better way to do what I'm doing above?
2) How can I get a consistent edge traversal direction? OR How can I detect the edge traversal direction?

**Comment by mikedh** [comment]
I think the issue getting consistent winding with that approach is because it's using `edges_unique` which are always sorted (so the original edge direction is lost). If you run `group_rows` you can get the edges with original direction:

```
unique = trimesh.grouping.group_rows(mesh.edges_sorted, require_count=1)
unshared_edges = mesh.edges[unique]
```

Then a traversal has a fighting chance haha. I don't recall offhand if `trimesh.graph.traversals` is directed or not (I suspect not) but you can always create a `networkx.DiGraph` from those edges:
```
nx.from_edgelist(unshared_edges, nx.DiGraph)
```

**Comment by DustinReagan** [comment]
Oh thanks, I hadn't noticed `group_rows`, that seems like it could be useful for several things I'm working on.
