### ISSUE TITLE
Shapely polygon from trimesh.path.path.Path2D

### ISSUE THREAD

**Issue by tomaso909** [mikedh/trimesh#11]
I have sliced a 3d mesh with yz planes into several 2d sections (i.e. Path2D objects). Now, I'd like to create Shapely polygons from these 2d sections. For doing so, I need a list of points as XY coords. However, if I use `Path2D.vertices`, I get a weird polygon because the vertices are un-ordered. Is there any way to get an ordered list of the vertices composing a Path2D object?

Obviously I cannot use the python `.sort()` method.

**Comment by mikedh** [comment]
Did you check the path.polygons_full and path.polygons_closed attributes? To generate those the path object is automatically traversing the path.vertex_graph.

**Comment by tomaso909** [comment]
Great, that is what I needed.
I didn't know I could get the Shapely.polygon directly with` path.polygons`.
Thank you Michael.

**Comment by Phornp** [comment]
Hello,
I have exactly the same problem but cant find anything in the polygons module to convert it correct to a `shapely.geometry.polygon.Polygon` object. When using the `polygon_closed` or `polygon_full` on a Path2D Object I get a shapely Polygon which is sometimes displaced.
Can anybody help me, please?
(I used the code in the examples to cut a stl-file in sections. Then I wanted to cut each section in lines with a defined distance. I did that with the `LineString.intersection.Polygon`-Method from Shapely. Perhaps there also exists something in the trimesh-package? Or am I so stupid and it is also possible when cutting the object in z- and the in x- or y-planes). 
I try to solve this problem for 3 days now...

**Comment by mikedh** [comment]
Hey, so what part isn't working? The polygon is probably displaced if you are using the to_planar method without specifying the matrix. 

I updated the section example: https://github.com/mikedh/trimesh/blob/master/examples/section.ipynb check out In[12] to show how to pass the matrix. Also I added In[10] which shows a linestring-polygon intersection.

Best,
Mike

**Comment by Phornp** [comment]
hey mike, 
thanks! I think the problem was, that I didnt overgave the T-Matrix... I will try it these days. Thank you very much so far!!!!
regards,
Philipp

**Comment by Phornp** [comment]
hey again,
the problem was the T-Matrix (to_3D). I want to add, that in my case it was important to overgive the Identity matrix to get the original coordinates again... If somebody has the same problem...
and thank you for the library, mike. Really great.
Philipp

**Comment by nick-parker** [comment]
Hey Mike, sorry to rez this issue but I've found a pretty key flaw in the polygon conversion code and/or the section code. Nested shapes like a tube within a tube correctly slice into 3D paths and project into 2D but then everything past the outermost solid ring gets erased in polygons_full. 

Plotting the 2D path shows all interior paths as green, which I suspect means they're all getting classified as holes when they ought to be alternating?

I'll try to hunt down the exact issue and update you here, but I wanted to fire off a report because other work is about to pull me away and I'm not sure when I'll get around to tackling this.

Example stl: https://drive.google.com/open?id=17MYvSdjpzB1wfEwDJ3xYWxP_bdbt0DK_

![Example mesh](https://user-images.githubusercontent.com/2140551/75928384-46f91880-5e3c-11ea-9f16-0203a3924d39.png)

Path2D section: 

![Example Path2D cross section

](https://user-images.githubusercontent.com/2140551/75928357-39dc2980-5e3c-11ea-9ed4-b175c9860425.png)

Result of `MultiPolygon(my_path2d.polygons_full):
![image](https://user-images.githubusercontent.com/2140551/75929335-5c6f4200-5e3e-11ea-95d3-c511c9b1e87c.png)

**Comment by mikedh** [comment]
Oh yeah it should be checking for that in `trimesh.path.polygons.enclosure_tree` by looking at the degree in the enclosure tree. A quick test with the same topology as your example seems like it's giving the correct answer:
```
p = trimesh.path.util.concatenate(
        [trimesh.path.creation.circle(radius=r)
         for r in range(1, 5)])
```
Returns:
![topo](https://user-images.githubusercontent.com/1403074/75930724-4020d480-5e41-11ea-888c-ba9e17239b01.png)

```
In [5]: p.polygons_full
Out[5]: 
array([<shapely.geometry.polygon.Polygon object at 0x7f80c40f4dd8>,
       <shapely.geometry.polygon.Polygon object at 0x7f80bc2f6320>],
      dtype=object)

```

Is it possible the sections are not fully closed? If you run `path.fill_gaps` does it do anything?

**Comment by nick-parker** [comment]
Here's the enclosure tree for mine:

![image](https://user-images.githubusercontent.com/2140551/75932835-6dbc4c80-5e46-11ea-99ec-250cbb4cd2e7.png)

The mesh is definitely closed properly, so if the sections aren't that's a different bug. path.fill_gaps didn't do anything.

I'm running my own fork with some changes though, let me try to reproduce on master real quick.

**Comment by nick-parker** [comment]
Yeah looks like it's something I changed that caused the issue, doesn't reproduce on master. Sorry to bug you!

**Comment by mikedh** [comment]
No worries, glad it was a version issue in this case! Though for future people looking at this I actually have another suspect that could possibly touch this too: vertex merging behavior. After a bunch of asks for "no merging by default" my compromise solution was to to consider vertex normals if populated, and only merge vertices that had the same position, vertex normal (if loaded), and UV (if loaded). 

For 3D printing-ish stuff, I now load every mesh using `loaded = trimesh.load(file_name, merge_norm=True, merge_tex=True)`. Behavior on STL files (which have no vertex normals) wouldn't change, but OBJ could.
