### ISSUE TITLE
[Enhancement] Clockwise orientation for interior rings of sections

### ISSUE THREAD

**Issue by nick-parker** [mikedh/trimesh#128]
The convention in Shapely is for interior rings to be oriented clockwise. Currently trimesh doesn't seem to enforce orientation at all, cutting a simple rectangular tube I imported from an stl results in two concentric ccw squares using to_planar and polygons_full.

The convention could be enforced (when viewing Path3D sections from the +Normal side of the plane which created them) by making intersection segments point along plane_normal X face_normal

As a workaround for others in need of properly oriented polygons, shapely has a handy utility: `
```
from shapely.geometry.polygon import orient
fixed_poly = orient(poly) #This will make exterior rings CCW and interiors CW
```
I looked at intersections.py for a bit, going to try to implement this myself at some point. I'm mostly making this issue to find out if you've tried this before and run into major roadblocks.

**Comment by mikedh** [comment]
Hey Nick- actually trimesh is already checking to force all rings (interiors and exteriors) to be counterclockwise. 

Since it's already consistent, it is pretty easy to reverse the interiors of polygons_full on creation. I made the change and added a test in https://github.com/mikedh/trimesh/commit/952d3807849646595fb892d39d75ec8010c3b157. 

Thanks for the report!
