### ISSUE TITLE
Garbled glb/gltf export

### ISSUE THREAD

**Issue by andy-5** [mikedh/trimesh#1286]
Thank you for this great library.

### Incorrect export

In a larger scene, I noticed that some objects were garbled after export to .glb/.gltf. But the data in the Trimesh objects was correct. 

Some of the objects in question were simple (but different) cube-like meshes. Here is a screenshot of one of the objects that got exported incorrectly (left) and the correct mesh (right):
![garbled-glb-export](https://user-images.githubusercontent.com/2477826/125739329-977144c4-07f9-440c-ada4-b1f41db224b0.png)

The vertices are correct, but the indices are exported incorrectly.

### Cause

After some debugging, I tracked it down to the hashing of the faces array, used to deduplicate buffers in gltf (introduced in https://github.com/mikedh/trimesh/pull/1182).

The affected objects had (in my case) the same number of vertices, and thus similar, but different, definitions of their faces, e.g.:

```python
faces1 = np.array([0, 1, 2, 0, 3, 1, 0, 2, 4, 0, 4, 5, 5, 6, 3, 5, 3, 0, 7, 1, 3, 7,
    3, 6, 4, 2, 1, 4, 1, 7, 5, 4, 7, 6, 5, 7], dtype=np.int64).reshape(-1, 3)
faces2 = np.array([0, 1, 2, 0, 3, 1, 2, 4, 0, 5, 4, 2, 6, 3, 0, 6, 0, 4, 6, 1, 3, 6,
    7, 1, 2, 7, 5, 2, 1, 7, 4, 5, 7, 6, 4, 7], dtype=np.int64).reshape(-1 ,3)
```

Using the default `fast_hash` (`zlib.adler32`, when `xxhash` is not installed), they hash to the same value:

```python
>>> zlib.adler32(faces1.tobytes()) == zlib.adler32(faces2.tobytes())
True
```
So only one of the index buffers got exported, and the other meshes incorrectly shared the same buffer.

### Possible solutions

The easiest workaround is to just install `xxhash`, which fixes this. Maybe `xxhash` should be promoted to a hard dependency? For the latest release, there seem to be [wheels for Linux, macOS and Windows](https://pypi.org/project/xxhash/#files), so maybe the comment https://github.com/mikedh/trimesh/blob/73a41c3659b7962a07c8ebd509bca2455010e34f/trimesh/caching.py#L25-L27 is not valid anymore?

Another fix would be to use a better hash function as a slower, but correct, default, like for example md5.
Adler-32 is not well suited for small buffers, like in my example. Quoting [Wikipedia](https://en.wikipedia.org/wiki/Adler-32#Weakness):
> Adler-32 is weak for short messages because the sum A does not wrap.

**Comment by mikedh** [comment]
Thanks for the excellent debugging! Yeah seems like the simplest solution is to just switch `fast_hash` to a better hash function rather than abuse a checksum like it was doing. Playing around with some options:

```
In [3]: a = np.random.random((1000, 3))

In [16]: %timeit hashlib.sha256(a).hexdigest()
43.4 µs ± 860 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)

In [17]: %timeit xxhash.xxh3_64_hexdigest(a)
1.13 µs ± 5.84 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

In [18]: %timeit hashlib.md5(a).hexdigest()
29 µs ± 1.97 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)

In [20]: %timeit trimesh.caching.crc32(a)
6.6 µs ± 144 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

In [21]: %timeit hash(a.tobytes())
9.63 µs ± 143 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

In [22]: %timeit xxhash.xxh64(a.tobytes())
2.21 µs ± 48.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

```

Wow, xxhash is way faster. Python built-in hashing is a distant second, although my concern is that [it may have similar issues to the CRC]( https://stackoverflow.com/questions/2070276/where-can-i-find-source-or-algorithm-of-pythons-hash-function). In https://github.com/mikedh/trimesh/commit/da125f7288f76f1097bdc4b3fd5aa3ec2b7e86a0 I changed to to use xxhash3, falling back to xxhash2, falling back to MD5. The downside of this is anyone without xxhash installed is going to see cache checks get 4.4x slower, but I think that's probably OK. 

It seems like in practice collisions with a real hash function (MD5 or xxhash) should essentially never happen.
