### ISSUE TITLE
save_image not working consistently

### ISSUE THREAD

**Issue by Kojon74** [mikedh/trimesh#1301]
I am trying to take a screenshot of my mesh using save_image. I have currently set the parameter visible=False since whenever I set it to true, I get the new window showing the mesh which then crashes my entire program (and I end up having to force quit Python and restarting my whole script).

However, when I do this sometimes I don't actually take a picture of the mesh and I just get a gray screen, and other times it works perfectly fine.

**Comment by mikedh** [comment]
Yeah, unfortunately save_image is pretty unreliable in general because of platform differences which there isn't much we can do about. I've found the most reliable thing for headless rendering in general is using LLVMpipe software rasterization which works pretty well, here's a docker example: https://github.com/mikedh/trimesh/tree/master/examples/dockerRender
