### ISSUE TITLE
Allow for getting transforms between arbitrary connected nodes in `trimesh.scene.transforms.SceneGraph`

### ISSUE THREAD

**Issue by manuelli** [mikedh/trimesh#1321]
Currently the [`get`](https://trimsh.org/trimesh.scene.transforms.html#trimesh.scene.transforms.SceneGraph.get)  method of `SceneGraph` throws an error if there isn't a path in the **directed** graph. As an example consider the following code snippet which runs without any errors

```
s = trimesh.Scene()
s.graph.update(frame_from='world', frame_to='A', matrix=tra.translation_matrix([1, 0, 0]))
world_t_A = s.graph.get(frame_from="world", frame_to="A")[0]
```

If we try to get the transform `from=A, to=world`

```
s.graph.get(frame_from="A", frame_to="world")[0]
```

then it throws the error

```
File "/usr/local/lib/python3.6/dist-packages/trimesh/scene/transforms.py", line 141, in get
    zip(path[:-1], path[1:])]
  File "/usr/local/lib/python3.6/dist-packages/trimesh/scene/transforms.py", line 140, in <listcomp>
    matrices = [edge_data[(u, v)]['matrix'] for u, v in
KeyError: 'matrix'
```

I believe the problem arises from the fact that there is a path from `world --> A` in the directed graph (e.g. `g = s.graph.to_networkx()`) but there isn't a directed path `A --> world`. However there is a path in the undirected graph `g_undirected = networkx.DiGraph.to_undirected(s.graph.to_networkx())` so we can definitely compute the transform  **from A to world** by inverting some matrices. Namely,

```
A_t_world = s.graph.get(frame_from="A", frame_to="world")[0]
```

It would be great if `SceneGraph` supported this functionality, which is similar to the ROS tf [`lookupTransform`](http://wiki.ros.org/tf/TfUsingPython) method.

**Comment by mikedh** [comment]
Agreed! Yeah dropping `networkx` was so we could allow minimal installs to load `gltf`/`glb` which I think was probably worth it, although this issue is one of the downsides of that. Seems like the implementation options are:

1) `SceneGraph` tries to find a path between both nodes, failing that it finds a `base_frame` transform for both nodes and then inverts one of them.
2) `EnforcedForest.shortest_path` does the logic internally: if it reaches the `ValueError` block it switches to the other node, then exits when it sees a node that is part of the other nodes path. `shortest_path` returns either `path, direction` (where direction is 1 or -1). Or `shortest_path` returns `path_a, path_b` where `path_b` is `None` when the second node is above the first (which would only requiring inverting one matrix).
