### ISSUE TITLE
if _validate remove_degenerate_faces() does not set height

### ISSUE THREAD

**Issue by ynotstartups** [mikedh/trimesh#134]
instead of 

    if self._validate:
        self.remove_duplicate_faces()
        self.remove_degenerate_faces()

should it be

    if self._validate:
        self.remove_duplicate_faces()
        self.remove_degenerate_faces(height=tol.merge)

because in the documentation of def process(self): in base.py:180

    '''
    If self._validate:
        3) remove degenerate triangles, defined as a triangle
        with one edge of their rectangular 2D oriented bounding
        box as less than tol.merge, which is 1e-8 by default
        4) remove duplicated triangles
    '''

**Comment by mikedh** [comment]
Hey, actually there was a bit of [debate about that](https://github.com/mikedh/trimesh/pull/133). The docstring is outdated and I'll update it, but the short story is that `remove_degenerate_faces` was removing faces that were definitely bad, but probably could have been kept.

Now, the behavior is to only remove faces that have a cross product of their edges smaller than machine epsilon (tol.zero). If `remove_degenerate_faces` is called manually with a height specified, it then removes triangles with any edge of its 2D OBB smaller than that specified height. 

Also, the default is now to not remove any triangles ( `validate=False`). 

Happy to discuss the right thing to do here, as it seems like there isn't a clear correct thing. It's a question of how much does trimesh do automatically vs. explicit function calls.

**Comment by ynotstartups** [comment]
I think it depends on your (you as an author of the library) targeted user for trimesh. 

Personally, I use it for preparing stl files for 3d printing, automatically remove bad/small triangle is acceptable, or even desired. But I can imagine for engineer, they could be mad if you automatically remove faces. 

Does this discussion extend to whether merge_vertices() shuold be called automatically? since we are automatically merging vertices, like removing close vertices. 

P.S. Wow, this is some big changes.. I should have listen to "The API is mostly stable, but this should not be relied on and is not guaranteed; install a specific version if you plan on deploying something using trimesh as a backend."

**Comment by mikedh** [comment]
Hey, the goal of the change were primarily to make things less magical so faces don’t disappear when the user wasn’t expecting it. 

Currently, degenerate faces are currently in two buckets:

1) Faces with a cross product smaller than tol.zero are removed by remove_degenerate_faces called with no arguments. These were previously silently removed when you requested `mesh.faces` or `mesh.face_normals` which was confusing.  Thinking about it a little more, this is not the greatest metric because you can have faces with edges all above tol.merge have a cross product below tol.zero:

```
In [61]: v = trimesh.unitize([[2,3,0], [-2,3,0]]) * 1e-7

In [62]: np.linalg.norm(np.cross(*v))
Out[62]: 9.230769230769232e-15
```

2) Faces with one edge of the OBB less than a specified height, removed by remove_degenerate_faces with a height (often tol.merge). This is a nice metric because it handles the obvious cases (duplicated vertex, 3 colinear points) and has good behavior around small values:
```
n [74]: v = trimesh.unitize([[2,3,0], [-2,3,0]]) * 2e-8
In [75]: tri = np.vstack((v, [0,0,0])).reshape((-1,3,3))
In [76]: trimesh.triangles.nondegenerate(tri)
Out[76]: array([ True])

In [77]: v = trimesh.unitize([[2,3,0], [-2,3,0]]) * 1e-8
In [78]: tri = np.vstack((v, [0,0,0])).reshape((-1,3,3))
In [79]: trimesh.triangles.nondegenerate(tri)
Out[79]: array([False])
```


In [this branch](https://github.com/mikedh/trimesh/tree/degenerate), I changed the behavior to:
- Use *only* the OBB metric to declare a face degenerate
- keep validate False by default, but if True, have it use the OBB metric (ignore cross product magnitude completely)
- face normals with a cross product smaller than tol.zero will be returned as zero magnitude vectors

I think that's an improvement, though I'm open to suggestions.
