### ISSUE TITLE
mesh_plane function

### ISSUE THREAD

**Issue by robotechstar** [mikedh/trimesh#1340]
The `mesh_plane` function finds the intersection points quite fast. I'm curious about the theory behind that one. Could you suggest a paper/document containing the formula/theory behind it?

**Comment by mikedh** [comment]
Haha thanks for noticing! Unlike boolean operations cross sections are pretty fast/reliable because the majority of the work is in a single dot product which numpy/BLAS compute extremely quickly. There's no paper to reference, but the [implementation](https://github.com/mikedh/trimesh/blob/master/trimesh/intersections.py#L18) is pretty well commented and straightforward.
