### ISSUE TITLE
Rigid registration returns a reflected mesh even if the optional parameter `reflection`, of the `procrustes` function, is set to `False`

### ISSUE THREAD

**Issue by blunovart** [mikedh/trimesh#1417]
Hi!
As usual, awesome job! 🥇

I am trying to perform a rigid registration of a mesh with respect to a target mesh (the `other_mesh`) using the `mesh_other` function. However, the rototranslation matrix that is returned from the function is such that to reflect the mesh.

I have tried to change the default value of the `reflection` parameter of the `procrustes` function to `False` but I still get a reflected mesh.

I am using Trimesh  3.9.25.

Unfortunately, I cannot share this mesh, but I am wondering If you have ever experienced that problem and how I can prevent the reflection of the mesh.

Thanks!

**Comment by mikedh** [comment]
Ah, never seen that but it seems like it is very likely this line: 
https://github.com/mikedh/trimesh/blob/46f48f1df0bbba304b1ef9673417d3ede5256172/trimesh/registration.py#L242-L243

No idea how to fix it, but seems like we should be unit testing the determinant (i.e. -1 if reflection, else +1) somewhere. PR's welcome!

**Comment by blunovart** [comment]
Thanks for the suggestion! I am going to check that.

**Comment by mikedh** [comment]
Hey, actually I was updating the test to iterate though all possible combinations of options in #1429, and I actually reverted my own "fix" as it looks like the original code was always producing matrices `determinant > 0.0 if not reflection`. What was the determinant of the matrix when you saw this issue?

**Comment by fabricecarles** [comment]
I found same issue in trimesh 3.18.3
```
transform_to_occ, cost = trimesh.registration.mesh_other(target_mesh, source_mesh, samples=500, scale=False, icp_first=10, icp_final=50, reflection=False)
```
output can be flipped (or not) this is sample dependant

**Comment by rompur** [comment]
We encountered the same issue in **Trimesh 4.4.1**. The resulting matrix from `trimesh.registration.mesh_other` sometimes included reflections/mirroring (i.e., the determinant was negative), even when the `reflection` parameter was set to `False`.

### Problem Analysis

After analyzing the code, I believe the problem is caused by the following section of  `trimesh.registration.mesh_other`:

```python
# permutations of cube rotations
# the principal inertia transform has arbitrary sign
# along the 3 major axes, so try all combinations of
# 180 degree rotations with a quick first ICP pass
cubes = np.array(
    [
        np.eye(4) * np.append(diag, 1)
        for diag in [
            [1, 1, 1],
            [1, 1, -1],
            [1, -1, 1],
            [-1, 1, 1],
            [-1, -1, 1],
            [-1, 1, -1],
            [1, -1, -1],
            [-1, -1, -1],
        ]
    ]
)
```

The issue seems to arise from cube rotations with uneven flips, which cause reflections/mirroring in the resulting matrix.

### Proposed Solution

To resolve this, we used only flips that do not result in reflections:

```python
# only flips that are not reflections
cubes = np.array(
    [
        np.eye(4) * np.append(diag, 1)
        for diag in [
            [1, 1, 1],
            #[1, 1, -1], # causes reflection
            #[1, -1, 1], # causes reflection
            #[-1, 1, 1], # causes reflection
            [-1, -1, 1],
            [-1, 1, -1],
            [1, -1, -1],
            #[-1, -1, -1], # causes reflection
        ]
    ]
)
```

This adjustment seem to work well in our case. Perhaps the code could be modified to check the `reflection` parameter and exclude these combinations when reflections are not desired.
