### ISSUE TITLE
mesh loading not order preserving?

### ISSUE THREAD

**Issue by riaqn** [mikedh/trimesh#147]
I realized recently that when a mesh is loaded, the vertex order is not preserved? That is, mesh.vertices[0] is not the first vertex in the original mesh file.

the format I'm using is OFF.

I feel this is fundementally problematic, and can cause serious confusing to users.

**Comment by mikedh** [comment]
Hey, this actually came up very recently in [this thread](https://github.com/mikedh/trimesh/pull/117#issuecomment-379094386) 

OBJ supports some weird cases so its hard to guarantee ordering in all cases, but the fix in https://github.com/mikedh/trimesh/commit/c019a25874fec33ca6ec3094621743711a29623f should preserve vertex and face order in the simple cases if you load your mesh with processing disabled:
`mesh = trimesh.load('stuff.OBJ', process=False)`

You can get the update with:
`pip install --upgrade trimesh`

**Comment by mikedh** [comment]
Oh sorry, I misread OBJ vs OFF. Disabling process should work in that case too, though its not in tests.

**Comment by riaqn** [comment]
Thanks for the lightening reply @mikedh. This workaround works for me.

I suggest making that the default value if it won't cause substantial loss in functionalities.

Thank you.

**Comment by sqwhong** [comment]
I also found that when calling 
```python
path = mesh.outline()
```
The order of vertices attribute in mesh and path is different. I wonder if there's a way to address this issue.

**Comment by tuqubao** [comment]
import numpy as np
import trimesh

p = r'C:\Users\admin\Desktop\test\test_02.obj'

mesh = trimesh.load( p, process = False )
print(mesh.vertices)

the vertex order is not preserved. how to do that? 
I has  upgraded trimesh, with pip install --upgrade trimesh, the problem is still existe.

the print 
[[-2.5 -2.5  2.5]
 [-2.5 -2.5  2.5]
 [-2.5 -2.5  2.5]
 [ 2.5 -2.5  2.5]
 [ 2.5 -2.5  2.5]
 [ 2.5 -2.5  2.5]
 [-2.5  2.5  2.5]
 [-2.5  2.5  2.5]
 [-2.5  2.5  2.5]
 [ 2.5  2.5  2.5]
 [ 2.5  2.5  2.5]
 [ 2.5  2.5  2.5]
 [-2.5  2.5 -2.5]
 [-2.5  2.5 -2.5]
 [-2.5  2.5 -2.5]
 [ 2.5  2.5 -2.5]
 [ 2.5  2.5 -2.5]
 [ 2.5  2.5 -2.5]
 [-2.5 -2.5 -2.5]
 [-2.5 -2.5 -2.5]
 [-2.5 -2.5 -2.5]
 [ 2.5 -2.5 -2.5]
 [ 2.5 -2.5 -2.5]
 [ 2.5 -2.5 -2.5]]

the answer should be:
 -2.5 -2.5 2.5 
  2.5 -2.5 2.5 
 -2.5  2.5 2.5 
  2.5 2.5 2.5 
 -2.5 2.5 -2.5 
  2.5 2.5 -2.5 
 -2.5 -2.5 -2.5 
  2.5 -2.5 -2.5

the number of vertex and order is wrong. 

how to fix the problem?

**Comment by tuqubao** [comment]
I found the code from wavefront.py
235                    current['v'].append(attribs['v'][int(f_split[0]) - 1])

attribs['v'] store all the vertex message, include position and order. but current['v'] copy vertex base on face message. and final the return mesh include the current['v'] message is face to vertex info. the vertex's order message is miss. I hope you fix the bug maybe that is 
current['v'] = attribs['v']
because attribs['v'] have a right vertex's info.

**Comment by tuqubao** [comment]
I doubt setup process = False will work the problem, because the load_wavefront() return the data is miss order info, you can't rebuild it.

**Comment by zhan-xu** [comment]
Yeah same here. Sometimes load_mesh gets the wrong number of vertices, although I used process=False

**Comment by mikedh** [comment]
Hey, this is likely from the way OBJ encodes vertices, vertex normals, and vertex UV's. Faces like this:

```
f 3//5 8//5 4//5
```

Will have vertices expanded as we consider `2//1` as a different vertex from `2//3` because if the *position* is the same but the *texture coordinate* is different we have to refer it differently in the simple data structure trimesh uses. I'd suggest using a different format with a more aligned data structure (i.e. `GLB`) if this is a major issue for you.

**Comment by aluo-x** [comment]
I was also very confused recently by the differing number of vertices between the orig OBJ & the loaded mesh data. Any thoughts on reducing the difference?

**Comment by mikedh** [comment]
Hey, have you tried loading with `process=False`?
```
In [1]: import trimesh
f
In [2]: fn = 'duck.obj'

In [3]: with open(fn, 'r') as f:
   ...:     text = f.read()
   ...:     

In [4]: text.count('v ')
Out[4]: 2399

In [5]: m = trimesh.load(fn)

In [6]: m.vertices.shape
Out[6]: (2277, 3)

In [7]: m = trimesh.load(fn, process=False)

In [8]: m.vertices.shape
Out[8]: (2399, 3)
```

**Comment by aluo-x** [comment]
First thing I tried. The mesh was a level 4 icosphere directly exported from Blender. So it was well behaved.

**Comment by mikedh** [comment]
I just checked the blender export and it's exporting faces like:
`f 3//5 8//5 4//5` 

Which are being unmerged to provide the flat data structure. If we add Yet Another Boolean Kwarg to skip this (`skip_uv`? `skip_unmerge`? idk) we can get the count to match:

```
In [2]: a = trimesh.load('ico4.obj', process=False)

In [3]: a
Out[3]: <trimesh.Trimesh(vertices.shape=(3840, 3), faces.shape=(1280, 3))>

In [4]: a = trimesh.load('ico4.obj', process=False, skip_uv=True)

In [5]: 

In [5]: a
Out[5]: <trimesh.Trimesh(vertices.shape=(642, 3), faces.shape=(1280, 3))>

In [6]: with open('ico4.obj', 'r') as f:
   ...:     print(f.read().count('v '))
   ...:     
642

```

But as far as I can tell it does generally mean discarding UV's and normals. Happy to add if it'd be useful!

**Comment by aluo-x** [comment]
Would be much appreciated! Its unfortunate that OBJ has so many edge cases.

**Comment by mikedh** [comment]
@aluo-x I added the `maintain_order` kwarg to the OBJ loader and to the `unmerge_faces` function, let me know if this doesn't work for you. It's explicit enough that any reordering of vertices from the original would then be a bug we can fix as opposed to just unexpected behavior :smile::

`trimesh.load('model.obj', process=False, maintain_order=True)`

**Comment by youmingdeng** [comment]
> @aluo-x I added the `maintain_order` kwarg to the OBJ loader and to the `unmerge_faces` function, let me know if this doesn't work for you. It's explicit enough that any reordering of vertices from the original would then be a bug we can fix as opposed to just unexpected behavior :
> 
> `trimesh.load('model.obj', process=False, maintain_order=True)`

Thanks, it's work for me

**Comment by aefull** [comment]
In addition to the vertices, Edge also comes in a different order.
Neighbor vertices is the same mesh, 
Sometimes it returns differently.
