### ISSUE TITLE
Is there a way to use less memory?

### ISSUE THREAD

**Issue by jschoormans** [mikedh/trimesh#1510]
Hi, I love the trimesh library, I am actually using it to make automated 3d printable files. 
However, I run into some issues, as my code needs to run on a server and too much memory is used. 
For example, when I load a .stl file that is 20 MB, it loads ~80 MB in python memory as a trimesh file. For comparison, if I load it using another library such as pyvista, the memory load is much less. Are there any ways to decrease this??

Thanks!
Jasper

**Comment by mikedh** [comment]
Hey, yeah this is probably mostly due to use of `float64` and `int64` everywhere. If you find-replace `float64` and `int64` to `float32` and `int32` in `trimesh.base` the following goes from 40mb -> 20mb of use for the example object:

```
    import trimesh
    import psutil

    before = psutil.virtual_memory()

    # creates an approximatly 16mb STL file                          
    m = trimesh.creation.icosphere(subdivisions=7)

    after = psutil.virtual_memory()

    print((before.available - after.available) / 1e6)
```

That being said I'd expect this to probably result in some fairly confusing precision issues particularly when transforming and doing other operations.

**Comment by jschoormans** [comment]
Thanks a lot Mike! 
I'll try this :) Cutting memory use in half will help a lot
