### ISSUE TITLE
OFF export, single precision representation?

### ISSUE THREAD

**Issue by riaqn** [mikedh/trimesh#161]
I'm not sure how points are represented in trimesh, but it seems that the points in OFF exported is only single precision?

**Comment by mikedh** [comment]
Vertices are `np.float64` internally. OFF is an ASCII format so it's only exporting to a certain number of digits, [looks like 8](https://github.com/mikedh/trimesh/blob/master/trimesh/io/export.py#L74-L77).

The thinking was probably that `trimesh.constants.tol.merge` is 1e-8, so vertices closer than that are merged anyway. It would probably make sense to have a safety margin and make `digits=10` in that exporter.

**Comment by riaqn** [comment]
thank you @mikedh . I didn't know that close points are merged automatically - may I suggest turn this off by default? Users could be confused.

So is there anything I can do to export the float64 fully? AFAIK, 17 significant digits would suffice.

**Comment by mikedh** [comment]
I think the easiest thing probably would be to pass a larger number of digits to the OFF exporter, which should be possible once the build finishes for https://github.com/mikedh/trimesh/commit/e4899ab623ab3bacb1b0e8e864a04cd6fe4b33ff :

```
In [1]: import trimesh

# if you don't want it to merge vertices initially, turn off processing
In [2]: m = trimesh.load('models/featuretype.STL', process=False)

In [3]: export = trimesh.io.export.export_off(m, digits=17)

In [4]: len(export)
Out[4]: 157312

```

Most mesh formats are single precision- PLY supports double precision technically but the implementation in trimesh exports vertices as 32 bit floats,  as most files you see in the wild are 32 bit. That would be pretty easy to change, and is the most common (and nicest) mesh format that may support higher precision.

For merging vertices- if you pass `process=False` to the loader it won't merge. Merging is the default behavior because for watertight meshes many operations will be either wrong or useless without doing it (is_watertight, face_adjacency, etc). 

Best,
Mike

**Comment by riaqn** [comment]
Thank you @mikedh. I guess it wouldn't be reasonable to add `digit` argument to the main export function as it doesn't apply to binary format.

**Comment by riaqn** [comment]
Sorry to reopen the issue - I found that `digits` is just the number of digits after the decimal point? I feel "siginificant digits" would make much more sense.

**Comment by mikedh** [comment]
No worries- BTW I added kwarg passthrough, so you should be able to do a `mesh.export(file_type='off', digits=17)`.

I think changing to significant figure vs decimal count there might break things elsewhere- with the current (decimal count) way we're getting precision relative to the "pseudo fixed point" magnitude. By that I mean we're using floating point numbers but generally considering points closer than `tol.merge` (1e-8) the same point. 

Best,
Mike
