### ISSUE TITLE
Copying visuals when copying geometry

### ISSUE THREAD

**Issue by clemense** [mikedh/trimesh#1623]
Everything works as expected when doing the following (the exported sphere is green):
```
s = trimesh.creation.uv_sphere().scene()
s.geometry['geometry_0'].visual.face_colors[:, :3] = [0, 255, 0]
g = s.geometry['geometry_0']
g.export('/tmp/sphere.obj')
```

When doing the same with copying, this doesn't work (the exported sphere is not green):
```
s = trimesh.creation.uv_sphere().scene()
s.geometry['geometry_0'].visual.face_colors[:, :3] = [0, 255, 0]
g = s.geometry['geometry_0'].copy()
g.export('/tmp/sphere.obj')
```
Any idea - is this not a bug?  (the copy() method looks quite evolved and does a deep copy of the visuals....)

Additional hint: if I do the above -- but do `s.show()` before copying -- the exported sphere is green (?):
```
s = trimesh.creation.uv_sphere().scene()
s.geometry['geometry_0'].visual.face_colors[:, :3] = [0, 255, 0]
s.show()
g = s.geometry['geometry_0'].copy()
g.export('/tmp/sphere.obj')
```

How can I emulate whatever `show` does without visualizing the scene?  (is this a cache issue?)

**Comment by mikedh** [comment]
Ah yeah this is a symptom of the colors being too magical. Slicing the default colors moves the colors from the "cached" state (*not* copied) to the "is-user-data" state. `ColorVisuals.copy` should be fixed by the above commit (not released yet). I'm not sure what to do about these long-term. 

If you want a hotfix you can set the colors with an equal not a slice which immediately marks them as user-data rather than a "check cached default color MD5 for a user change":
```
In [3]: m = trimesh.creation.box()

In [4]: m
Out[4]: <trimesh.Trimesh(vertices.shape=(8, 3), faces.shape=(12, 3))>

In [5]: m.visual.face_colors = [0,255,0]

In [7]: m.visual._data.data
Out[7]: 
{'face_colors': TrackedArray([[  0, 255,   0, 255],
               [  0, 255,   0, 255],
               [  0, 255,   0, 255],
               [  0, 255,   0, 255],
               [  0, 255,   0, 255],
               [  0, 255,   0, 255],
               [  0, 255,   0, 255],
               [  0, 255,   0, 255],
               [  0, 255,   0, 255],
               [  0, 255,   0, 255],
               [  0, 255,   0, 255],
               [  0, 255,   0, 255]], dtype=uint8)}

```
