### ISSUE TITLE
Very small triangles pass through merge_vertices but cause issues in normal computation

### ISSUE THREAD

**Issue by Binaryhalibut** [mikedh/trimesh#179]
When using `triangles.normals()` the cross product of two sides of the triangle is first calculated, then unitized in `util.unitize()`.

When calculating this cross product, it is possible for vertices that are too far apart to be merged in preprocessing under the standard 1e-8 `TOL_MERGE` to result in sides with a cross product with norm  smaller than the 1e-13 `TOL_ZERO` specified in util.py

For example, a triangle with all sides having length 1.1e-8 will not be merged, but the cross product of two sides has length 1.1e-8 ^ 2 * sin (pi/3) = 1.0e-16, which is zero according to TOL_ZERO.

This causes `triangles.normals()` to deem the face invalid even though it passes through `base.merge_vertices()`.

This is mostly a problem in `apply_transform`, where `normals_pre` and `normals_post` can be invalid if the first face falls under this condition, which breaks `triangles.windings_aligned()` and causes an exception.

**Comment by mikedh** [comment]
Ah, good catch. A recent change in trimesh is to return 0- magnitude normal rather than NaN's (or magically removing the face) in this case. If you load meshes with `m = trimesh.load(file_name, validate=True)` it will remove faces with an edge smaller than tol.merge and avoid this case. 

Since that alignment check shouldn't care about scale, I changed the check to roughly normalize the triangles before doing the check in https://github.com/mikedh/trimesh/commit/2658c7cf5d83449b43f8ee4b98ea994c2cea515e

That fixed the test case I was experimenting on: if you do a `pip install --upgrade trimesh` are you still getting this?

Thanks for the report!

**Comment by mikedh** [comment]
Actually build isn't done: pip upgrade with the fix will be available when https://travis-ci.org/mikedh/trimesh/builds/391849129 finishes.

**Comment by mikedh** [comment]
I believe this to be fixed- feel free to reopen if you see after upgrading.
