### ISSUE TITLE
Memory and runtime issues with ICP

### ISSUE THREAD

**Issue by jpmaterial** [mikedh/trimesh#1929]
When running `trimesh.registration.icp()` with two medium-sized trimeshes (300k triangles), I'm getting an OOM after ~2h runtime (on a machine with 16 GB RAM). I'm now thinking about subsampling the "other" trimesh (of which only the points are passed). What is your opinion on this approach in general and on the best sampling strategy? (I'm considering uniform sampling [either among vertices or using Trimesh.sample()) or preferring points with high absolute vertex error.)

**Comment by Kiord** [comment]
Did you try the ICP with the vertices only ? `trimesh.registration.icp(mesh1.vertices, mesh2.vertices)`
If the second argument is a mesh, there is a call to `trimesh.proximity.closest_point()` at each iteration, which is a lot more expensive than the KDTree called otherwise.

Downsampling the meshe(s) by sampling surface surface should be a solution. 
I think it is worth looking at [Pytorch3D functions](https://pytorch3d.readthedocs.io/en/latest/modules/ops.html) such as `iterative_closest_point` and `sample_farthest_points`, they are super fast on GPU.

**Comment by jpmaterial** [comment]
Thanks, that's what I went with.
