### ISSUE TITLE
Set light in a scene

### ISSUE THREAD

**Issue by clemense** [mikedh/trimesh#193]
Hi,
Is it possible to set the light in a scene?
(I would like to visualize colored point clouds whose colors are not affected by the perspective of the camera; right now colors change drastically when rotating the point cloud in the viewer)
Thanks!

**Comment by mikedh** [comment]
Hey, right now the lighting is all [hardcoded in the viewer's gl initialization](https://github.com/mikedh/trimesh/blob/master/trimesh/scene/viewer.py#L129-L138), as the scene viewer was originally written more for "are there any triangles in this mesh" than general scene graph use. 

That being said, it would be nice if there were light and camera objects (maybe `trimesh.visual.Light`/ `trimesh.scene.lighting.Light` or something). I'm open to PR's, and may look in to doing that at some point.

**Comment by ifermion** [comment]
Hi @clemense ! 
I've faced the same problem and was trying to find a work-around. I ended up modifying several lighting parameters in /trimesh/viewer/windowed.py and restoring them once visualisation is done. I'm not sure if this is of the sort that you've been after.

The idea was to remove the diffused and specular reflection effects from the light source initiated by the function init_gl (https://github.com/mikedh/trimesh/blob/master/trimesh/viewer/windowed.py) and increase the ambient effect. I admit that this is a crude way, but I managed to get done what I wanted. 

To automate the process, I created two functions that I share here. The first is to initiate and modify the init_gl to be called before the initiation and the second is to be called at the end of the visualisation, in order to restore the original parameters of the init_gl. Please let me know if you already managed to solve this issue. 

``` 
def pyglet_overwriter():

    # This function is used to overwrite some pyglet window initialising parameters
    # in order to remove the diffused and specular reflection effects initialised by default, in order
    # for the visualisation to be uniform and not biased on the vector of the light source.
    # I admit this is a crude way, but I could not find a more direct way of solving this problem as I could not find
    # a way to call these relevant initialising parameters from within the trimesh library.
    #
    # The function looks for the windowed.py file in the installation path and makes a copy of it as a backup.
    # Then it modifies the file and this modified file will be used for initialising the pyglet window.

    import sys
    import os

    paths = sys.path
    for path in paths:
        if '/lib/python3.' in path:
            #print(path)
            break


    dir = '/site-packages/trimesh/viewer/'
    full_path=path+dir

    wdir = os.getcwd()
    os.chdir(full_path)


    os.popen('cp windowed.py windowed_backup.py') # Saving a backup of the original file for an eventuel restoration.

    os.popen('sed -i -e "s/rendering.vector_to_gl(.5, .5, 1, 1))/rendering.vector_to_gl(0,0,0,0))/g" windowed.py') #removal of specular effect
    os.popen('sed -i -e "s/rendering.vector_to_gl(1, 1, 1, .75))/rendering.vector_to_gl(0,0,0,0))/g" windowed.py') #removal of diffusive effect
    os.popen('sed -i -e "s/rendering.vector_to_gl(.1, .1, .1, .2))/rendering.vector_to_gl(.7, .7, .7, .7))/g" windowed.py') #modifying the ambient effect for better visualisation.

    os.chdir(wdir)

    return full_path

def pyglet_restore(full_path):

    # This function restores the original windowed.py file using the backup file saved earlier using pyglet_overwriter().
    # Hence this function should be called at the end of the file once the visualisation has been done.

    import os

    wdir = os.getcwd()
    os.chdir(full_path)
    os.popen('cp -f windowed_backup.py windowed.py')
    os.chdir(wdir)

    return
