### ISSUE TITLE
Memory Problem

### ISSUE THREAD

**Issue by Imageries** [mikedh/trimesh#196]
Hey Mike, first thanks for the nice library.

So I have build a simple converter with this but  I can't load big models. 
I will get a memory error as fast as I load a mesh with over 250000 to 500000 polys. 
The problem is that while the script is running it's not using all my memory, not close to it.
Does somebody got an idea what to do?
Greets :)

**Comment by mikedh** [comment]
Hey, I think that depends a lot on your machine and potentially the mesh format. How much memory do you have, and what format are you trying to load? For reference, on my older (i7-3770K with 32gb memory) machine:

```
In [4]: %timeit trimesh.load('src.ply')
10 loops, best of 3: 137 ms per loop

In [5]: m = trimesh.load('src.ply')

In [6]: m.faces.shape
Out[6]: (508454, 3)

```

**Comment by Imageries** [comment]
Hey, thanks for the quick reply.
I'm using a Threadripper1920x with 32 gb ram (2666mhz).
I'm loading a simple obj, when I load a reduced version of the model everything works fine.
Greets

**Comment by mikedh** [comment]
Ah, OBJ is also not the greatest format- binary PLY is probably a better bet if you have a choice.

**Comment by Imageries** [comment]
Alright it's working with stl. 
Do you think it's a problem with obj or could it be a hardware error?

**Comment by mikedh** [comment]
Gotcha. Due to the format layout the OBJ loader probably uses substantially more memory than the binary STL loader. That being said, loading a 500,000 triangle OBJ mesh on my machine (32 gb memory/Ubuntu) works fine. Is it possible you're running a 32 bit copy of Python? That would impose a 2gb memory limit (at least according to [this thread](https://stackoverflow.com/questions/5537618/memory-errors-and-list-limits)).

**Comment by Imageries** [comment]
Ah dude yeah, that was the cause :D 
It's working now, thank you very much.
I must have overlooked it when I downloaded it. 
Thanks again
