### ISSUE TITLE
crash when processing some meshes with degenerated faces

### ISSUE THREAD

**Issue by martinResearch** [mikedh/trimesh#1963]
Thank you for this amazing library.

## Problem:
I got  a crash when processing some meshes with degenerated faces.

In order to reproduce the bug, run:
```
import trimesh

mesh = trimesh.Trimesh(
    vertices=[[0, 0, 0], [1, 0, 0], [0, 1, 0], [1, 0, 0], [0, 1, 0], [1, 1, 0]],
    faces=[[3, 4, 4], [0, 1, 2], [0, 1, 2]],
    validate=False,
)
print(mesh.triangles)
mesh.process(validate=True)
print(mesh.triangles)
```
creates the exception:
`Exception has occurred: IndexError       (note: full exception trace is shown but execution is paused at: _run_module_as_main)
boolean index did not match indexed array along dimension 0; dimension is 2 but corresponding boolean dimension is 3` on line with code `self.faces = faces[mask]` in `Trimesh.update_faces`

## Fix:
add line with `self._cache.clear()` at the end of the method `Trimesh.update_faces`

**Comment by mikedh** [comment]
Thanks for the report and test case! Yeah since that case has both duplicate and degenerate faces it screws up the indexing, I just pushed a fix which does one `update_faces` on a combined mask, rather than one after the other. 

I changed `remove_degenerate_faces` (in-place) to `nondegenerate_faces -> list[bool]` but I should probably deprecate the in-place methods before releasing.
