### ISSUE TITLE
Deleting internal geometry

### ISSUE THREAD

**Issue by tejaskhot** [mikedh/trimesh#198]
Is there a way to delete internal faces of touching primitives? For eg, two touching cubes would have 2 internal faces where we wouldn't want to sample points from and hence those faces need to be deleted from the mesh.

**Comment by mikedh** [comment]
Hey, a couple options:

1) A boolean union of the two primitives. These can be flakey (try `engine='scad'`, it is quite a bit more robust than blender), but then you'd get one watertight mesh without internal geometry if it went right and can be sampled normally. 
2) Sample both independently, and then use KDTree queries to remove points from the second set that are within some radius of the first set. This is probably going to be the fastest and most reliable option, but will only really make sense in the "touching" case, and not do anything in instances where there is penetration.
3) Sample independently and then use `mesh.nearest.signed_distance` to remove points inside the  other mesh.
4) If mesh faces were actually exactly the same (which two cubes touching would not be, due to winding crossing the triangles) you could concatenate then then call `remove_duplicate_faces`

Best,
Mike

**Comment by mikedh** [comment]
I'm going to close for now- though feel free to reopen.
