### ISSUE TITLE
Extract UV map as .png file

### ISSUE THREAD

**Issue by rohit7044** [mikedh/trimesh#2057]
Hi, 
First of all tremendous work on trimesh. Thank you

I am trying to extract the UV map from a mesh. I see the coordinates in `visuals` but I want the extracted texture map processed in image format. Is there any way to do this?

**Comment by Kiord** [comment]
I am assuming your mesh only contains vertex colors ? (Else you would already have your texture)
If so you can project the vertex colors in the texture space and interpolate between them to recreate a texture.

```python
import numpy as np
from scipy.interpolate improt griddata
 
def compute_interpolation_map(shape, tcoords, values):
    points = (tcoords * np.asarray(shape)[None, :]).astype(np.int32)
    x = np.arange(shape[0])
    y = np.flip(np.arange(shape[1]))
    X, Y = np.meshgrid(x, y)
    res = griddata(points, values, (X, Y),  method='cubic')
    res[np.isnan(res)] = 0
    return res

tcoords = ... # you already have them
vertex_colors = ... # I assume you already have them
image_size = (512, 512) # create a 512 x 512 texture
texture_map = compute_interpolation_map(image_size, tcoords, vertex_colors) 
```

**Comment by math-sasso** [comment]
@Kiord I dont have the `tcoords  `and I dont know what it should be. Do you know how can I retrieve from the mesh?

```
mesh = trimesh.Trimesh(
                vertices=vertices_numpy,
                faces=faces_numpy,
                vertex_colors=color_numpy,
      )
```

Also, my goal is to import the mesh inside blender with color. Not sure which image_size would be required to that. 
Do you have some experience on that?

**Comment by Kiord** [comment]
Hello @math-sasso, they are _texture coordinates_ (or _uv coordinates_), a numpy array of size `number_of_vertices X 2` which indicates, for each vertex, its corresponding position in the two dimensional texture space. (see https://en.wikipedia.org/wiki/Texture_mapping).

If you load a mesh that has texture coordinates, you can access them like this `mesh.visual.uv`.
If your mesh has no texture coordinates, `mesh.visual` will be a [`ColorVisuals`](https://trimesh.org/trimesh.visual.html#trimesh.visual.ColorVisuals) instead of a  [`TextureVisuals`](https://trimesh.org/trimesh.visual.html#trimesh.visual.TextureVisuals) and will not have a `.uv` member.

Are you sure your mesh is textured in the first place ? (It may have just vertex colors)
Also it is not clear what are your inputs (before trimesh) and your outputs (what you want trimesh to do)

**Comment by Kiord** [comment]
The issue is on Blender side I'm afraid.

obj is not really a well defined format. Softwares use different conventions and it affects the vertex colors here.

glTF 2.0 should work though. 
- import the glb mesh as glTF 2.0 in blender
- select the object by clicking it
- in "Material tab", click new
- click Base Color to change its source, and click Color Attribute
- now you should see the colors in material preview mode

**Comment by math-sasso** [comment]
@Kiord thanks for the reply.

I followed the step by step, but when I click Color Attribute that is what happening. 
![image](https://github.com/mikedh/trimesh/assets/23565626/be329629-d942-45fc-9946-25b34d21b66a)

I unedrstand fom your explanation that colors will come configure inside the .glb file, so we sort of just need to "enable" it.

Did I miss something?

**Comment by math-sasso** [comment]
TripoSR also generates a video where I can see the colors exist before the export.
https://github.com/mikedh/trimesh/assets/23565626/c019c7bf-b575-4098-9b2a-427fdb49ea0b

**Comment by Kiord** [comment]
Are you in material preview mode ? [Screenshot_20240403_150331.jpg](https://github.com/mikedh/trimesh/assets/79104227/f0d53fe8-0f20-463b-8f9f-5a00e17b5bd4)

**Comment by math-sasso** [comment]
I can see it now thanks! 
However compared with the video gif I shared, the quality is way inferior.

![image](https://github.com/mikedh/trimesh/assets/23565626/23d381a4-95a6-4bb0-82db-0ad68b47e0f7)

**Comment by rohit7044** [comment]
Try opening the file on Meshlab or Microsoft 3D and see if it contains the same texture like the video.
If it doesn't, then there's issue on the processing pipeline of Tripod and better post the issue on that repository.
If it does show the texture right as you expect, then you need to figure out how to replicate that in blender.
Either way this situation remains out of scope for Trimesh
