### ISSUE TITLE
trimesh texture loading with PIL is toooo slow

### ISSUE THREAD

**Issue by Guptajakala** [mikedh/trimesh#2090]
Hi, currently when reading OBJ file with texture, PIL was used to read the image which is very slow, especially for higher resolution texture. Is there any plan to replace it by e.g. openCV? Or could you expose the image path in the [class](https://trimesh.org/trimesh.visual.texture.html)?

**Comment by mikedh** [comment]
Hey, what formats are you loading, also did you try profiling with pyinstrument? In general PIL is pretty fast and I rarely see it on profiles. In this apples to apples comparison loading a 420kb JPG into a numpy array they are essentially identical:

```
mikedh@luna:models$ ipython
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]

In [1]: from PIL import Image

In [2]: import cv2

In [7]: %timeit np.array(Image.open('capsule0.jpg'))
32 ms ± 1.06 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [8]: %timeit cv2.imread('capsule0.jpg')
34.4 ms ± 708 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

```

**Comment by Guptajakala** [comment]
I'm reading PNG format, which is a popular format for texture images. I was profiling my program and found a large portion of time was spent on PIL reading the image (4k resolution). 
```
img = np.array(mesh.visual.material.image)
```

I didn't do the profiling comparison myself between opencv and PIL, but there are a bunch of discussions showing opencv is (considerably) more favorable than PIL:
- https://towardsdatascience.com/image-processing-opencv-vs-pil-a26e9923cdf3
- https://www.kaggle.com/code/vfdev5/pil-vs-opencv/notebook

**Comment by mikedh** [comment]
Hey, I don't think it's necessarily true that opencv is in general faster than PIL.

- have you run `pip install --upgrade pillow`? In pillow's issue tracker there was some mention of a regression in 9.0 that was fixed in later versions
- can you run your script with pyinstrument to see what specific line is slow? Extracting the particularly slow image and then running the direct comparison above would be helpful for the pillow maintainers, and they are quite responsive to performance concerns (i.e. https://github.com/python-pillow/Pillow/issues/5986)

From a dependency standpoint pillow gets 15M+ downloads a week (5x more than opencv) and has very active development and great packaging (3mb wheels vs 50mb wheels for `opencv-python-headless` on pypi). I think from a trimesh standpoint it's probably not the right move to switch to opencv even though I use it for other stuff. A few isolated specific examples of the performance comparison would be the first step though for any path forward, i.e. it might be resolvable by changing PIL options without doing a ton of work.
