### ISSUE TITLE
Add Support for Textures

### ISSUE THREAD

**Issue by mmatl** [mikedh/trimesh#218]
I'm planning on tackling this soon, as I'd like to incorporate texture loading for use in `meshrender` (my work-in-progress OpenGL mesh renderer and viewer). Will start work in my fork in `BerkeleyAutomation` and run it by you once a PR is ready.

One thought -- should we start by supporting multiple textures per mesh, or is it okay for now to just support a single texture?

**Comment by mmatl** [comment]
@mikedh could you label this as an enhancement?

**Comment by mikedh** [comment]
Awesome, this would be terrific!

```
Loading the texture file itself will probably require imageio -- are you okay with introducing that dep? It's really lightweight.
```
ImageIO looks good to me, they seem active and support an impressive number of formats. Their heaviest dependency is `pillow`, which `trimesh.path.raster` also uses and is already in the `[easy]` install extras. TL;DR, sounds good to me.

I agree having a `TextureVisuals` object is the way to go, then  `trimesh.Trimesh.__init__` can switch between `ColorVisuals` and `TextureVisuals` depending on arguments passed.  Here's what I was thinking this would entail in terms of scope, though definitely don't feel obligated to do all of this (it's a ton of work haha):
- Create a `trimesh.visuals.TextureVisuals` object
  - If it can't load the image maybe just emit a `log.error` and fall back to a ColorVisual?
- Add some simple textured models to unit tests
  - Maybe put tests into a new file `test_texture.py`, I've been working in general to spread tests out over more files so that when one fails you don't have to sit through 5 minutes of unrelated stuff to debug.
- Update `trimesh.scene.viewer` to show texture
- Update `trimesh.io.wavefront` to load texture

Eventually:
- Update `trimesh.io.ply` for textures
- Update `trimesh.io.gltf` for textures (bonus, then the Jupyter notebooks will magically show textures too)
- (Maybe) add a color -> texture bake function, and texture -> color 

Does that sound sort of like what you were thinking?  Thanks for tackling this, and let me know if you'd like help with anything!

**Comment by mmatl** [comment]
That's exactly what I was thinking. I'll try to update the viewer to show them -- shouldn't be too hard with GL 1.0. Will let you know once I have a PR ready.

**Comment by mikedh** [comment]
Oh I missed this: `One thought -- should we start by supporting multiple textures per mesh, or is it okay for now to just support a single texture?`
I think a single texture is good, although I have no idea how common that is "in the wild." It seems like getting the easiest thing first is the way to go.

I also noticed that most of the common formats for ImageIO were coming from pillow (already a `trimesh` dependency), just for reference here are the supported formats for both libraries:
[Pillow formats](https://pillow.readthedocs.io/en/5.1.x/handbook/image-file-formats.html)
[ImageIO formats](https://imageio.readthedocs.io/en/latest/formats.html)

Though it seems like ImageIO is light enough and adds enough more formats to be worth the additional dependency over pillow (probably someone somewhere has meshes textured using RAW images :grin:).

**Comment by mmatl** [comment]
@mikedh Oh, didn't realize Pillow was already a dep! We can just stick with that for now for simplicity -- if someone really wants RAW in the future, we can change it then haha.

**Comment by EpicWink** [comment]
I already have a working implementation of bound materials to meshes, with multiple materials per mesh (I keep a reference array of which material a face uses, `face_materials`, and update this whenever `faces` is updated), using only `numpy` and `Pillow`. The only problem is that it is modeled off the [Wavefront OBJ](https://en.wikipedia.org/wiki/Wavefront_.obj_file) spec, whereas you probably want something more generic (such as the [glTF](https://en.wikipedia.org/wiki/GlTF) structure.

These materials support all the usuals, including plain colours, specular/diffuse/ambient colours/texture-maps, transparency. This might be more than what `Trimesh` is looking for, as rendering with lighting is probably beyond its scope.

`ImageIO` sounds like a great optional dependency, but `Pillow` supports most of the texture formats I've encountered.

**Comment by mikedh** [comment]
@EpicWink that sounds great! Are you able/willing to open source it with an MIT license? Maybe we can combine that and @mmatl's branch.

**Comment by mmatl** [comment]
@mikedh Sorry for the delay on this! Got sidetracked with some other stuff. I've been putting some thought into it, and I think the biggest issue I'm having is actually handling file IO for textures. Most of the existing IO methods expect a single file or file-like object, but textures are usually stored (and saved) in multiple files (e.g. you have `.obj` with `.mtl` and `.png` files all together). Figuring out how to smoothly integrate this with the existing IO structures is the main problem I'm having. Any input/ideas there?

**Comment by mikedh** [comment]
Haha no worries! Yeah IO does seem like a pain, especially because if an OBJ is passed as a file object how are we supposed to resolve paths. I think we'll probably have to search up `mesh.metadata['file_path']`. I just added some obj/mtl/jpg files, as well as a ZIP containing the same three files to test on. I'll see if I can poke around and get something not too horrible. I think the "passed file object without a path" is tough, but if meshes are loaded by filename it shouldn't be too bad.

Thanks for working on this!

**Comment by mmatl** [comment]
Yeah, the IO with file-like objects is the main problem (search + saving for real file paths isn't too bad). I'll put some more thought in.

**Comment by mikedh** [comment]
What do you think about manually passing an object when necessary, something like ([gist](https://gist.github.com/mikedh/cf2025e8119e43bef3f5c02de98b6695)):

```
import os
import trimesh

class FileSystemResolver(object):

    def __init__(self, source):
        """
        Resolve files based on a source path.
        """

        # remove everything other than absolute path
        clean = os.path.expanduser(os.path.abspath(str(source)))
        
        if os.path.isdir(clean):
            self.parent = clean
        # get the parent directory of the 
        elif os.path.isfile(clean):
            split = os.path.split(clean)
            self.parent = split[0]
        else:
            raise ValueError('path not a file or directory!')

    def get(self, name):
        with open(os.path.join(self.parent, name), 'rb') as f:
            data = f.read()
        return data

class ZipResolver(object):
    """
    Resolve file from a ZIP archive
    """
    def __init__(self, archive):
        self.archive = archive
    
    def get(self, name):
        return self.archive[name].read()
        
    
    

if __name__ == '__main__':

    # example of file system assets
    file_name = 'models/fuze.obj'
    f_res = FileSystemResolver(file_name)
    f_tex = f_res.get('fuze.obj.mtl')


    # example of zip resolver
    with open('models/fuze.zip', 'rb') as f:
        d = trimesh.util.decompress(f, 'zip')        

    z_res = ZipResolver(d)
    z_tex = z_res.get('fuze.obj.mtl')
    

        
    ### Examples (not implemented)

    # just works because resolver will be created in load
    #m = trimesh.load('models/fuze.obj')

    # needs resolver to be passed
    #with open(file_name, 'rb') as f:
    #    m = trimesh.load(f, file_type='obj',
    #                     resolver=FileSystemResolver(file_name))
        
```

Then we can create a resolver at the app level for ZIP/cloud buckets/file system/remote etc.
