### ISSUE TITLE
Typing issue for is_empty

### ISSUE THREAD

**Issue by friggog** [mikedh/trimesh#2187]
Recent releases cause mypy to fail when typing `is_empty` - https://github.com/mikedh/trimesh/blob/94b8ceacb3db0aa96fdebe721f243af4d01c2b5d/trimesh/parent.py#L42-L43

The abstract method is typed as a method but the implementation is as a property:
https://github.com/mikedh/trimesh/blob/94b8ceacb3db0aa96fdebe721f243af4d01c2b5d/trimesh/base.py#L1637-L1638

This means mypy fails with `truthy-function`

**Comment by mikedh** [comment]
Hey, yeah definitely wrong, seems like we could just add the property decorator to the parent and fix this. It would be nice to unit test all the type hints (https://github.com/mikedh/trimesh/pull/2188 ) as otherwise they're likely to be intermittently incorrect.

I thought this should have caught this bug:
```
pytest --typeguard-packages=trimesh test_mutate.py
```

However since the subclass has correct type hints the parent isn't caught. Any ideas on how to check these?

**Comment by friggog** [comment]
Do you have any mypy checks running? this usually turns up any typing errors for us, particularly if configured to be reasonably strict
