### ISSUE TITLE
Maintaining Dimension Order on wound_mesh.bounding_box_oriented.primitive.extents

### ISSUE THREAD

**Issue by jbudman** [mikedh/trimesh#224]
Hi,

I am trying to use the oriented bounding box method to obtain the dimensions of an object. It seems as though the order output by applying wound_mesh.bounding_box_oriented.primitive.extents to a mesh can vary.

E.g. print(mesh.bounding_box_oriented.primitive.extents) will output values in a different order at times

 Is there any more meta-data in the method we can use to determine which dimension is which? I'm thinking in terms of standard Length by Width by Height. 

Thanks again, 

Josh

**Comment by mikedh** [comment]
Hey Josh, yeah having a consistent order on returned OBB extents would be nice.

I'm not sure if "length/width/height" has meaning for 3D blobs with arbitrary transforms. I think the best you could do is ensure that `oriented_bounds` always returns extents that are sorted. It would have to also flip the transform correctly for the new extents order.

**Comment by mikedh** [comment]
This was coming up elsewhere (comparing extents of OBB's in `test_scene`) so I added a change and test to make sure returned OBB extents are always sorted rather than arbitrary, and also flips the transform to the new ordering: https://github.com/mikedh/trimesh/commit/f492ce3807725b3f0810d382b0720093f763ab97

The build just finished releasing, so you should be able to get it with `pip install --upgrade trimesh`

Let me know if you see any issues, and thanks for the report!
