### ISSUE TITLE
mesh.visual.vertex_colors

### ISSUE THREAD

**Issue by zeal-github** [mikedh/trimesh#226]
Thanks for your job! I have some question about the `display` function.
After I loaded a .ply file with the below headers:
```
ply
format ascii 1.0
comment Generated by PyMesh
element vertex 6890
property double x
property double y
property double z
property uchar red
property uchar green
property uchar blue
element face 13776
property list uchar int vertex_indices
end_header
```
I don't know why `mesh.visual.vertex_colors` is a `npoint x 4` matrix, like these:
```
[[ 59 255 167 255]
 [  3 255 147 255]
 [239 255 151 255]
 ...
 [143 255 163 255]
 [ 87   0 195 255]
 [123 111  31 255]]
```
the last value is all 255, but the first 3 value do not correspond to the value in the file.
`mesh.visual.face_color` is also a `nfacetsx4` matrix, but in my file, faces has not other propertics.
When I use `mesh.show()` to show the mesh in jupyter notebook, the color is all the same in the shape, even when I use 
```
for facet in mesh.facets:
    mesh.visual.face_colors[facet] = trimesh.visual.random_color()
```
So I'm rather confused about these problems. I look over the example provided by you, but I have not found the answer.

Oh, by the way, is there more tutorial about this project? Thanks for your contribution again!

**Comment by mikedh** [comment]
Hey, the color data type in trimesh is RGBA (red-green-blue-alpha), represented by an (n, 4) array of unsigned 8 bit integers. The last value (alpha) being 255 just means that the color is fully opaque. 

In `trimesh`, you can define either face colors or vertex colors, and then the one not defined is derived. IE your mesh sets vertex colors, and then each face color is generated from the average vertex color.

>> the last value is all 255, but the first 3 value do not correspond to the value in the file.

This is either a  bug, or possibly because vertices were merged on load. You can turn that off with:
`mesh = trimesh.load('stuff.ply', process=False)`

The colors not showing in a jupyter notebook is because colors are only supported in the GL preview window at the moment. You're the second issue this week with that, I'll work on adding colors to the GLTF exporter (which the jupyter preview uses) when I get a chance. If you force the preview to use a pyglet window the colors should show:
`mesh.show(viewer='gl')`

Thanks for the report!

**Comment by mikedh** [comment]
I added face/vertex color support to GLTF/jupyter notebooks in https://github.com/mikedh/trimesh/commit/a40d9e2cab5951a8c5df1a7b9c2727f781ae0eab, if you do a `pip install --upgrade trimesh` you should be able to get it. I also added [an example](https://trimsh.org/examples/colors.html) with colors in the jupyter viewer.

**Comment by zeal-github** [comment]
@mikedh Thank you so much! All problems have been solved. I very appreciate your work, it helps me a lot.

**Comment by JoeLambourne** [comment]
Hi,

I still see something odd happening with colored meshes in a notebook.  I use code like this

```
color_map = np.array(
    [[235, 85, 79, 255],  # ExtrudeSide
    [220, 198, 73, 255], # ExtrudeEnd
    [113, 227, 76, 255], # CutSide
    [0, 226, 124, 255],  # CutEnd
    [23, 213, 221, 255], # Fillet
    [92, 99, 222, 255],  # Chamfer
    [176, 57, 223, 255], # RevolveSide
    [238, 61, 178, 255]  # RevolveEnd
    ], dtype=np.uint8
)

mesh = trimesh.load_mesh(obj_file, process=False)
tris_to_segments = np.loadtxt(seg_file, dtype=np.uint64)   # Loads an np array with index into color_map for each triangle
facet_colors = color_map[tris_to_segments]                        # Build the array of colors shape = (num_tris, 4)
mesh.visual.face_colors = facet_colors
mesh.show()
``` 
When I display with `viewer='gl'` then I get what I expect in the gl window.  Inside the notebook it looks like it's blurring colors over the faces though.  The mesh is watertight without any duplicate vertices, so it needs to be rendered with facet colors rather than vertex colors. 
![image](https://user-images.githubusercontent.com/17026486/115544535-a01f4800-a29a-11eb-824c-0d2182aee6ff.png)
