### ISSUE TITLE
Volume method wrong?

### ISSUE THREAD

**Issue by Sheradil** [mikedh/trimesh#2260]
Hey there,

I can't help myself (and I am probably wrong), but can it be that the volume calculation has an error?

The attached mesh is more or less simple. I reconstructed it from a point cloud using different methods (the original poisson reconstruction, the poisson reconstruction in meshlab and a reconstruction based on a binary linear program). The point cloud was taken from a usual container that is used to transport goods on trucks. These are usually 2.45m*2.65m*length. The length can vary, but usually it is 8-14m. 
So for a 14m container the volume is ~91m^3.

![Screenshot from 2024-08-07 11-53-57](https://github.com/user-attachments/assets/59a40b73-b626-4210-9ca8-b8956c025f5f)

I used MeshLab and it displays  105.3m^3 for the volume. Which is odd, because it is too much. I quickly checked the width, height and length with the measurement tool. Width (2.32m) and height (2.57m) are ok. The length is ~12.07m, which would give a volume of 72m^3 (as you can see in the picture, the values are not perfectly measured, but the error should not make that much of a difference). The container was filled with boxes, though. So in the back section is actually no free volume. So the volume should be smaller than the 72m^3, because the boxes take away free volume.

That made me question the volume calculation of MeshLab. Looking for alternatives, I used trimesh to do the volume calculation. I wanted to use a library that is (almost) free of dependencies so that I can be certain that not the same implementation (code, maybe it is the same algorithm) is used.

And trimesh gave me the same results (not exactly, but close enough).

Looking at the mesh, I am certain that the volume is not as high as calculated.
That's why I think that there is an error.
I attached the mesh as reference. 
[mesh.zip](https://github.com/user-attachments/files/16521672/mesh.zip)

Did I make a mistake or overlooked something or is there a bug? 
I know it is unlikely, because it would also mean that there is a bug in MeshLab as well. 
But these results look so wrong.

**Comment by mikedh** [comment]
Hey, does the mesh pass `mesh.is_volume`? `mesh.volume` is an [implementation](https://github.com/mikedh/trimesh/blob/480ece1455a6564fb6d6d4a22b9741ee0a94bf69/trimesh/triangles.py#L206-L231) of the surface integral method described in the nice [Geometric Tools notes](    http://www.geometrictools.com/Documentation/PolyhedralMassProperties.pdf). If the mesh isn't totally watertight the numbers will definitely be weird (and transform dependent, because it's not really a volume), you could also look at `mesh.convex_hull.volume` which is often more robust. 

For what it's worth some of the tests around the mass properties include comparing volume and inertia calculated with that method to primitives and some ground-truth from Solidworks.
