### ISSUE TITLE
scene.set_camera() ignored in notebook

### ISSUE THREAD

**Issue by foobarbecue** [mikedh/trimesh#237]
`.set_camera` successfully sets the position of the camera when displayed using pyglet, but has no impact on the camera position in notebook.

As a minimal case:

```
import trimesh
scene = trimesh.Scene(trimesh.primitives.Box())
scene.set_camera(angles=(0.5, 0, 0), distance=5, center=(0,0,0))
scene.show()
```

appears the same in jupyter notebook with and without the third line, but different if run from a command line.

**Comment by mikedh** [comment]
Ah yeah, the three.js viewer uses an [auto- centering function](https://github.com/mikedh/trimesh/blob/master/trimesh/resources/javascript/load_base64.js#L5-L35) rather than the camera transform. Also GLTF doesn't currently export the camera transform at all (IIRC). This could be a nice improvement!

**Comment by mikedh** [comment]
Should be fixed by https://github.com/mikedh/trimesh/commit/ef477f06fa88a5f6e5e923f9c1614bc587efaaab.
