### ISSUE TITLE
Smooth 3D object STL

### ISSUE THREAD

**Issue by bbarroqueiro** [mikedh/trimesh#318]
Hello

As far as i could understand trimesh does not have mesh smoothing, right? Therefore, i developed a function to the the job. However, i am not experienced in programming , if you can take a look at the code and see what you think and give some advice, i would appreciate it....

If you think this can be of any use to the community feel free to include it in trimesh 

[filter.txt](https://github.com/mikedh/trimesh/files/2856242/filter.txt)

Another thing, do you have any idea how can i generate  volume mesh (TET4) in Python environment?

The best regards
BBarroqueiro

**Comment by mikedh** [comment]
Nice! Yeah adding various types of smoothing would be great! With regards to tet meshing, have you looked in to [meshpy](https://mathema.tician.de/software/meshpy/)?

I'm always happy to accept PR's, some quick suggestions for your filter module:

- Rather than accepting an `id_filter` parameter to one function, I would divide it into three functions, in a file `smoothing.py`, `smoothing.laplacian`, `smoothing.taubin`, etc. 
- I'd suggest adding some default arguments to parameters that make a "best guess" for filtering. It currently requires careful reading of the docstring to figure out what to pass, especially with the conditionals
- I would try to avoid looping through vertices if at all avoidable. Sometimes you can do one tight loop or list comprehension to construct an array that you can then do vectorized operations on, and it is quite a bit faster.
- sometimes to avoid looping you can use sparse matrix operations on `mesh.faces_sparse`, which on some operations can be like 10000x faster than looping
- profiling with [pyinstrument](https://github.com/joerick/pyinstrument) or [cProfile](https://docs.python.org/3/library/profile.html) can be very helpful to figure out which parts are slow
- rather than `np.shape(array)[0]`, I'd suggest `len(array)`. You can use ipython magic to see the differences between equivalent calls:
```
In [3]: a = np.random.random(1000)

In [4]: %timeit np.shape(a)[0]
268 ns ± 24.3 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

In [5]: %timeit a.shape[0]
95.1 ns ± 4.32 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)

In [6]: %timeit len(a)
73.4 ns ± 1.33 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)

```

**Comment by bbarroqueiro** [comment]
Hello... thanks for the feedback...

I ended up using sparse matrix to avoid for lopping on vertices, which is much faster...
I will make a PR...

Regards
