### ISSUE TITLE
Add functions for searching mesh surfaces

### ISSUE THREAD

**Issue by petebachant** [mikedh/trimesh#35]
It would be useful to be able to find from a given point (specifying an optional search direction):
- [x] Nearest vertex
- [x] Nearest face
- [ ] Nearest face normal vector
- [ ] Nearest triangle center

There all seem easy enough to write up, but interpolation onto the surface would be maybe even more useful. Let me know what you think and I may try to work up a PR.

**Comment by Marviel** [comment]
I've had to write my own code to do some of this. (nearest face, nearest vertex). Would be cool if there was a faster way to do it. (R-Trees perhaps?)

The implementation I made is just a search through the list of all vertices / faces.

**Comment by mikedh** [comment]
Good idea, and any PR's would be much appreciated!

**Nearest vertex** is easy, you can just query a scipy kdtree on the vertices.:
```
tree = m.kdtree()
pid = tree.query(points)
```
Unfortunately last time I looked in to adding the kdtree to the cache there were memory management issues which led to hard crashes, so the KDtree (and triangles_tree) has to be instantiated when you use it.

**Nearest triangle center** would be easy (`scipy.spatial.cKDTree(mesh.triangles_center)`) but may not be as generally useful as other things.

**Nearest face index and nearest point on surface** would be super useful, but is definitely more work. You might be able to use the nearest method of triangles_tree to avoid having to do a point- triangle query on every single face (which is going to be pretty slow).

I think the first step for the face queries is writing a good point-triangle function. One option is to assemble a corresponding list of triangles and points (with stacking/tiling) and then throw them into a function in trimesh.triangles that doesn't exist yet. That would at least get most of the heavy lifting into a few numpy calls rather than having to loop over anything. A prototype for that function:

```
# for development
from trimesh.triangles import *

def nearest_point(triangles, points, triangles_normals=None):
    '''
    Given a list of corresponding triangles and points, find the nearest point on each triangle to the given point. 

    Arguments
    --------------
    triangles: (n,3,3) float, triangles in space
    points:    (n,3) float, Cartesian points in space that correspond to triangles
    triangles_normals: (n,3) float, unit normal vectors of each triangle. 
                                     if not passed, generated from cross products

    Returns
    --------------
    nearest:  (n,3) float, Cartesian points on triangle
    distance: (n,) float, distance from input point to nearest point on triangle
    '''

    triangles = np.asanyarray(triangles, dtype=np.float64)
    points    = np.asanyarray(points, dtype=np.float64)

    if len(triangles) != len(points):
        raise ValueError('every triangle must have ONE corresponding point!')
    if triangles_normals is None:
        triangles_normals = normals(triangles)

    # do the things
    pass
```

One way you might use triangles_tree to assemble the list of point- triangle queries. There are going to be some edge cases that probably require playing around with num_results (and possibly adding an intersection query to generate a complete triangle candidates list):
```
In [1]: tree = m.triangles_tree()

In [2]: point = np.array([0,0,0], dtype=np.float64)

In [3]: bound_check = np.append(point, point + trimesh.constants.tol.merge)

In [4]: bound_check
Out[4]: array([ 0.,  0.,  0.,  0.,  0.,  0.])

In [5]: list(tree.nearest(bound_check, num_results=1))
Out[5]: [0]

```

**Comment by mikedh** [comment]
Hey, I haven't had much time to work on this lately but I did add a nearest point- triangle (for corresponding pairs) function in https://github.com/mikedh/trimesh/commit/820247f45b3e926247eded4e05f2ba1f9d1f8739

I also added a naive 'check every point against every triangle' function to trimesh.nearest, and added a helper to the base object in https://github.com/mikedh/trimesh/commit/2bdee8052dfae0f1791ce50f624852c377fbfcaf so you can do `mesh.nearest.on_surface(points)`

My thought was to only use the naive function with the giant intermediate arrays to validate an r-tree- based method, but irritatingly I've been thus far unable to get my r-tree method to give the same answer so I haven't committed it. For small meshes this works OK for now, and the helper method can be switched to a faster/better backend function later. 

I did some quick validation and a unit test, but it would be useful and much appreciated if you see this giving a crazy answer to put the mesh and query in this thread. 

Docstring for nearest point on surface method:
```
Given a NON- CORRESPONDING list of triangles and points, for each point
find the closest point on any triangle.

Does this by constructing a very large intermediate array and 
comparing every point to every triangle.

Arguments
----------
triangles: (n,3,3) float, triangles in space
points:    (m,3)   float, points in space

Returns
----------
closest:     (m,3) float, closest point on triangles for each point
distance:    (m,)  float, distance
triangle_id: (m,)  int, index of closest triangle for each point
```

**Comment by petebachant** [comment]
Mike, your work is much appreciated! I will let you know when I get a chance to test the new search against my own naive solutions.

**Comment by mikedh** [comment]
Cool, may want to pull again. I added a much quicker tree- based method, and a bunch of unit tests. The prior nearest point on triangle was missing a clip. I'm going to close this for now as I think 'nearest point on surface' is pretty solid.
