### ISSUE TITLE
PLY reading does not work?

### ISSUE THREAD

**Issue by sukysjonas** [mikedh/trimesh#37]
Hi

Older (much older) version of trimesh worked fine for me.
After updating (now 2.2.11), it does not manage to read the PLY file, I get
```
File "/usr/lib/python2.7/site-packages/trimesh/io/ply.py", line 131, in elements_to_kwargs
faces = elements['face']['data']['vertex_indices']['f1']
ValueError: no field of name vertex_indices
```
Any ideas on what is the issue in the updated version?

**Comment by mikedh** [comment]
Hmm, probably got borked when I added support for ASCII ply. Any chance you could send me the file to test on?

**Comment by sukysjonas** [comment]
Sure,

I uploaded it here:
https://server.sukys.lt/owncloud/index.php/s/bWAvzpTVo0KlMhS

Thanks

**Comment by mikedh** [comment]
Looks like the exporter you used set the face element key as 'vertex_index' instead of 'vertex_indices'. Also, both trimesh and meshlab get a NaN value for the last face, which made the merge_vertices remove everything. In https://github.com/mikedh/trimesh/commit/bd20fa174264f0aee0eb1fc46758b03b148ce4cd I changed the loader to be more robust to different names for the data, and also a function to remove the NaN values cleanly on load. I'm not sure why this mesh would have been loadable with an older version of trimesh, but it should work now.

**Comment by sukysjonas** [comment]
I see, thanks for quick reply and fix.
I am aware of the last NaN, but this did not seem to cause any issues so far.
Your patch works now, thanks!

**Comment by mikedh** [comment]
Glad its working for you!
