### ISSUE TITLE
gltf: Support loading / saving separated files (e.g. images)?

### ISSUE THREAD

**Issue by EricCousineau-TRI** [mikedh/trimesh#430]
At present (6d11104), it looks like `gltf.py` does not support loading / saving all types of separated files, like images.

The following would be nice (but prolly not super simple):

* Have a flag that says "it's OK to ignore meshes", in which case they're ignored, and it just loads the vertices. (would satisfy my current application)
* Support `"uri"` specification for other types beyond buffers.

Looks awesome overall, though!

**Comment by mikedh** [comment]
Hey Eric, yeah I mainly use it for GLB files with everything embedded. Not loading externally referenced images is an oversight fixed in https://github.com/mikedh/trimesh/commit/761713142331194ffbde80e5ffc842a652d801c8 which should be released and up on pypi now.

- For “ignore meshes” is that a generally applicable thing? If you just need vertices, you might want to export them to GLTF with `mode` set to `GL_POINTS`, then `trimesh` and other libraries would be able to load them correctly as point clouds without any flags. `trimesh` doesn’t currently support that but it would be pretty easy and consistent with the format. 
- Do you have examples of other `uri` types? The examples in the spec appear to be all file system locations.

**Comment by EricCousineau-TRI** [comment]
> For “ignore meshes” is that a generally applicable thing? [...]

D'oh! I had meant "ignore textures" as you had implemented in your PR - sorry for the miscomm!

> Do you have examples of other uri types? [...]

Not really, just filesystem paths, and they all tend to be relative to the GLTF file.

And thank you for doing that so quickly!

**Comment by EricCousineau-TRI** [comment]
Implementation question: I was perusing `gltf.py` a bit to see what might be required to permit something like `export_gltf(..., separate_files=True)`.

Overall, it looks pretty straightforward (I think?), but the main information loss would be losing texture file names, which is important for my application - however, I can always post-process the JSON after the fact.

That being said, is there a way in `trimesh` to pass the filename of the texture? (for this specific application, and for debugging / traceability?)
Perhaps something like `NamedByteStream`, which could duck-type imitate `bytes`, and maybe have an optional `filename` or `source_uri` field?

**Comment by mikedh** [comment]
Hey, right now the GLTF exporter [doesn't export texture at all](https://github.com/mikedh/trimesh/blob/761713142331194ffbde80e5ffc842a652d801c8/trimesh/exchange/gltf.py#L489-L527). If we replaced that block with actual texture exports, seems like the logical way to do what you're suggesting might be that texture images get exported using some variant of the `name` attribute on the  [`trimesh.visual.texture.PBRMaterial`](https://github.com/mikedh/trimesh/blob/87e6652e4e18939ea821476fedad0f3df05c77e9/trimesh/visual/texture.py#L203-L261).

**Comment by mikedh** [comment]
Added GLTF texture export to requested enhancements list, closing for now.

**Comment by EricCousineau-TRI** [comment]
Sweet, thanks!
If this crops up for us again and we take a whack at your proposed approach, I'll either ping on this issue or on the enhancement tracker.
