### ISSUE TITLE
Mesh not loaded correctly

### ISSUE THREAD

**Issue by Puttichai** [mikedh/trimesh#44]
Hi, I have the following error when loading a mesh.

I am trying to load [this off file](https://gist.github.com/Puttichai/925b0fbe9c75d37cba7dff3bad621fe3) by
```python
import trimesh
mesh = trimesh.load_mesh('chair.off', 'off', process=False)
```
The header in the off file is
```
OFF
37580 74488 0
```
But then the loaded mesh has only 74487 faces. Do you have any idea what's going on here or do I miss anything?
Thank you very much.

**Comment by mikedh** [comment]
Hey- what's probably happening here is that the automatic generation of face normals through cross products (since OFF doesn't include normals) detected a zero- area face and removed it.

You can verify this by checking the datastore (before accessing mesh.faces):
```
print(m._data['faces'].shape)
```

The reason face normals are auto-generated and degenerate faces are removed when you access mesh.faces is so that there is no chance of getting an inconsistent shape between mesh.face_normals and mesh.faces

I agree the silent alteration is potentially questionable, however the alternatives seems to me to be bad:
 - have mesh.face_normals potentially include NaN entries (would dump warnings everywhere and be annoying).
 - don't do the check when accessing mesh.faces (which would mean mesh.faces and mesh.face_normals potentially have different shapes depending on access order)
- keep doing the same thing but output a log.warning when there's a degenerate face (this could be OK)
- do the check but raise an error when there's a degenerate face (annoying)

I'm open to suggestions :)

**Comment by Puttichai** [comment]
I see. Thanks a lot for the clarification :))
I think putting warning should be good. At least one knows what happens.
But do you mean that after calling once `m.faces()`, there is no way to get the original set of faces?

The reason I need original faces is that I am using a mesh segmentation algorithm which outputs a label for each face. Missing faces causes discrepancy between labels and faces. How I fix this now is that I access faces directly via `m._data['faces']`.

**Comment by mikedh** [comment]
Cool, I added the warning. Oh, the other thing you could do (I forgot I added a flag for this- I should work on docs at some point):

```
mesh = trimesh.load('blah.off')
mesh._validate = False #turn off face/normal validation

print(mesh.faces.shape)
```

**Comment by Puttichai** [comment]
Awesome. Thank you!

**Comment by mikedh** [comment]
NP.
