### ISSUE TITLE
Passing arguments in different order to Camera object changes results

### ISSUE THREAD

**Issue by mikedh** [mikedh/trimesh#451]
Continuation of #449 

Passing arguments in different order to `trimesh.scene.cameras.Camera` objects screws up our bookkeeping, and returns a wrong result:

```
        base_res = (320, 240)
        updated_res = (640, 480)
        fov = (60, 40)

        # start with initial data                                        
	base_cam = g.trimesh.scene.Camera(
            resolution=base_res,
            fov=fov)
	# update both focal length and resolution                        
        base_focal = base_cam.focal
	base_cam.resolution = updated_res

        assert not g.np.allclose(base_cam.focal,
                                 base_focal)


        # try the same thing in reverse order                            
	base_cam = g.trimesh.scene.Camera(
            resolution=base_res,
            fov=fov)
        # update both focal length and resolution                        
        base_cam.resolution = updated_res
        base_focal = base_cam.focal

        # TODO: this currently fails, but should pass as a minor order change                 
        # should not break our bookkeeping                               
        assert not g.np.allclose(base_cam.focal,                       
                                  base_focal) 
```

A short list of parameters:

| Parameter | Depends On |
| - | - |
| Resolution | nothing? |
| FOV | resolution, focal length | 
| focal | resolution, FOV |

**Comment by jackd** [comment]
... I'm not sure I follow what the issue is here. Since `fov` is specified in the constructor, it will remain fixed and `focal` will vary with resolution. Setting resolution mutates the camera state, so you get a different `focal` depending on whether you `get` it before vs after the `resolution` `set`.

If you want `focal` to be constant (rather than `fov`) you can set it in the constructor (or any time before the resolution set) in which case `fov` will change upon resolution change. Even doing something like `cam.focal = cam.focal` will switch the "fixed" variable to `focal` from `fov`.

Specifying both in the constructor might lead to misleading results, so maybe it would be best to raise an error in this case?

**Comment by mikedh** [comment]
I played with this a little more, and I see your point. Since it's a computed property assigning in a different order does make a difference, so it's not crazy that our thing behaves differently depending on the order. 

I was chatting with someone about this, and they had an interesting suggestion: "If you didn't express your focal length in pixels you wouldn't have that dependence." That is probably an entirely new bag of worms however.
