### ISSUE TITLE
when i export stl from volume Memory Error ? How to solve?

### ISSUE THREAD

**Issue by selvakarna** [mikedh/trimesh#476]
when i export stl from volume Memory Error ? How to solve? any parameters to convert stl on export stl using trimesh?

**Comment by mikedh** [comment]
How many faces does the mesh have? How much memory does your computer have?

**Comment by selvakarna** [comment]
Hi @mikedh , my computer have 32GB RAM,  volume image shape approximately 1000 X 1000 X 2000,

**Comment by selvakarna** [comment]
Hi @mikedh ,


Traceback (most recent call last):
  File "cc.py", line 170, in <module>
    img=np.array(extracted_image)
MemoryError

**Comment by mikedh** [comment]
One quick thing to check is that you are running a 64 bit OS rather than a 32 bit (as the memory limit is different). 

In general you are right at the limit with that, unless I did the math wrong:
`((1000*1000*2000) * 8 (bytes per point)) / (1e9, conversion to GB) = 16 GB`

I would suggest more memory, or lower resolution in the volume image as the quick and easy solution. If you reimplemented everything in an iterative manner (instead of vectorized) in cython you could probably get it to be equally performant with much less memory usage, but that is out of scope for `trimesh` and would be a huge amount of work.
