### ISSUE TITLE
Surpising default loading behaviour, i.e. Trimesh(..., process=True)

### ISSUE THREAD

**Issue by asnt** [mikedh/trimesh#484]
Thanks for this great package with many helpful components. I'd like to report some of my experience with it in case it might help improve things.

The Trimesh object seems to do some processing of a mesh upon loading. While I understand it is useful in some cases, it might not be the desired behaviour in others. This has caught me by surprise and took me some time to figure out. This seems a recurrent issue (#222, #435).

In my use case, I typically have a reference mesh and some deformed versions of it. All of them should keep the same structure for comparison purposes, even if containing artefacts. While setting `process=False` works, it wasn't intuitive to me at first. It made me look for a bug where there wasn't any. I maybe also missed a warning about this in the docs.

My suggestion would be to keep the mesh as it is by default (i.e. `process=False`) and if at all needed the user can look for and enable to additional processing steps.

Again, thanks for your efforts in creating this package.

**Comment by mikedh** [comment]
I think this is a consequence of varying use cases. We've walked back what `process=True` does over the last year or two, to just merging vertices and removing `NaN` values, but I could see how it could catch people unaware. 

My use case is part data exported from CAD packages, and thus you *always* want vertices merged (similar use cases include 3D printing, collision models for robotics, CAD analysis, etc). If you were dealing with models for visual purposes, you would *almost never* want vertices merged. It seems like it boils down to what the use case is, and I've arbitrarily chosen my own as the default. 

I'll definitely add a line in the README that mentions the behavior to minimize surprise. I'm pretty hesitant to change the default though, one way or the other one of those two groups is going to have to explicitly pass something to `process`.

Thanks for the report!

**Comment by paulmelnikow** [comment]
My use case is mostly analysis of meshes in correspondence, where the vertex indexing and faces must be preserved exactly as serialized; otherwise correspondence can get thrown off. I also need `process=False`, and only want `process=True` if I'm doing something one-off and unusual like importing an STL. In a lot of cases `process` will have no effect on the files I'm loading, though depending on the specific mesh it might… so forgetting to include `process=False` would be a bit of a gotcha.

Is there a way to load meshes using the Trimesh constructor, or is `trimesh.load()` the way to do it?

Global state would be an option to let developers set their own default, though it seems like a bad solution because it makes the behavior from within a library rather unpredictable.

Another option would be to force developers to choose one or the other by adding `trimesh.load_cleaned()` and `trimesh.load_strict()` and in v3 throwing a deprecation warning in `trimesh.load()`. It'd prevent surprises!

**Comment by asnt** [comment]
@mikedh +1 for mentioning this in the README. See #485 for a suggestion.

**Comment by mikedh** [comment]
@paulmelnikow I guess my question is, does `process=False` behave as you need it to? If it does, then just making sure you pass the flag seems preferable to adding additional structures. If it's critical for your application, I'd make my own load function which does what I want and add a bunch of `assert` checks:

```
def load_noproc(file_obj, file_type=None, **kwargs):
    # if someone tried to process say nah
    kwargs['process'] = False
    result = trimesh.load(file_obj=file_obj, file_type=file_type, **kwargs)
    if hasattr(result, 'metadata') and 'processed' in result.metadata:
        assert not result.metadata['processed']
    return result
    
```

Somewhat related; OBJ files have an index method that makes them not great if you need to preserve correspondence: faces referencing different v/vt/vn coordinates will cause v/vt/vn to be masked in ways you might not expect, I'd recommend PLY or STL if you can.

@asnt thanks for the PR documenting this!

**Comment by paulmelnikow** [comment]
Passing `process=False` is a reasonable thing to do, though since I use the library in many small libraries and scripts, I end up needing to copy and paste that a lot.  I could publish another package with `load_noproc()` in it, though I'd still have to train other developers to do use that function instead of using `trimesh.load`, because of the occasional weird edge cases it causes. I'm fairly convinced that there isn't a good default here, though respect this is your call. 😀 

> Somewhat related; OBJ files have an index method that makes them not great if you need to preserve correspondence: faces referencing different v/vt/vn coordinates will cause v/vt/vn to be masked in ways you might not expect, I'd recommend PLY or STL if you can.

I noticed before you don't recommend OBJ. I use OBJ almost exclusively for meshes in correspondence and haven't run into problems with indexing. Can you clarify what you mean?

As far as I can figure, STL is not good, because it can't preserve specific triangle indexing between a mesh in memory and a mesh on disk. The serialized vert order gets generated from the face order, so if there is anything out of order, it's going to be lost. For example, if I have a mesh in correspondence and remove a bunch of the faces and the corresponding verts, and then save it and load it, the vert ordering will be different. Furthermore, vert numbering varies depending on the how the loader combines the verts.

I also make pretty heavy use of groups in OBJs (though they are admittedly quite annoying to parse and write).

I have run into differences in ways certain OBJ loaders handle triangulation or quad/higher poly faces, though I don't think that's what you're meaning.

PLY works fine, though I appreciate that OBJs are more inspectable.

**Comment by mikedh** [comment]
Haha I guess the things that make OBJ tough to support is also the thing that makes writing an *exporter* so easy (which probably explains the popularity): OBJ files are just a jumble of lines, and the position of lines relative to other lines matters. There is no header to parse so data is all over the place. 

If I could wave a magic wand and choose the most common in-the-wild format, I'd pick GLB 2.0 in a heartbeat. It does everything, has an [awesomely specific spec](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0), you can easily parse the JSON header then load binary blobs super fast, meshes are just "list of faces, list of vertices, list of UV's, etc" (no "faces are `v/vt/vn`"), it supports PBR materials, etc. GLB2 feels like the future, OBJ feels like a legacy format that had no good alternatives for a long time.

BTW, if you use face groups heavily, the new exporter currently doesn't have support for them for the reasons you mentioned (annoying and slow parsing). Though if you can figure out a way to support them in the new loader, PR's would be appreciated!
