### ISSUE TITLE
vertex_normals as average of adjacent face_normals

### ISSUE THREAD

**Issue by dbukenberger** [mikedh/trimesh#506]
The default way to compute vertex normals in trimesh is as the average of the faces' normals adjacent to a vertex.
I just noticed that while testing some other stuff and the normals of a simple cube just looked so wrong.
Due to the triangulation, normals on corner-vertices are not `(1,1,1)/sqrt(3)` as one would expect.

I thought this is kind of a crude way to determine the vertex normals.
Is this done on purpose - maybe for the sake of simplicity?
If not, I have some code laying around with a more suitable weighting for the normals which I could add + tests of course. =)

**Comment by mikedh** [comment]
Haha I was going to protest that we area-weighted that, but looking at the [sparse matrix](https://github.com/mikedh/trimesh/blob/465a84a0f3e3068b71dad29b232f415656c47dd5/trimesh/geometry.py#L302-L311) it's just averaging every adjacent face normal as you say. Yeah definitely just done for simplicity and speed, the sparse matrix operations are shockingly quick. 

Here's a simple triangulation of a box, looks like the weight will be `[2, 2, 1]` in the corner rather than the more reasonable `[1, 1, 1]`: 
![box](https://user-images.githubusercontent.com/1403074/61962195-00366c80-af97-11e9-9606-d69787b10e99.png)

Yeah better weighting would be great! Looking at this mesh it's not clear to me how to get the right answer... do you only average *unique* normals? That seems like it would do the trick but possibly loose the rapid nature of a sparse matrix operation. PR's super welcome!

**Comment by mikedh** [comment]
Fixed by PR, thanks!
