### ISSUE TITLE
trimesh documentation

### ISSUE THREAD

**Issue by adrianbutscher** [mikedh/trimesh#51]
Hi,

My apologies if this is not the right place for this question.  Could you please tell me how to generate the documentation for the trimesh library?  I have not yet found the readme that explains how it is done!  Many thanks.

Adrian Butscher

**Comment by mikedh** [comment]
Hey Adrian- the docs are mostly a placeholder at the moment and need a bunch of work (PR's welcome 😁) which is why there's no link in the readme. That being said the API reference builds OK, and they're automatically built on commits at https://trimesh.readthedocs.io/en/latest/ 
or you can go into docs and run
`make html`

If you want you can check out the sphinx tutorials for more info.

**Comment by adrianbutscher** [comment]
Michael,

Thanks for your super-quick reply :) I have been browsing the various files in the trimesh module.  I must say, they are incredibly well-documented and cleanly written in a way which resonates well with my training as a mathematician (rather than a computer scientist).  I am looking forward to playing with the module. 

I succeeded in compiling the html docs.

Adrian

**Comment by mikedh** [comment]
Glad they built, and thanks for the positive reinforcement 😁!
