### ISSUE TITLE
trimesh.sample.sample_surface_even gives wrong number of samples

### ISSUE THREAD

**Issue by damdamce** [mikedh/trimesh#558]
Hi, thanks for the neat library!

I have a problem with trimesh.sample.sample_surface_even though:

```python
import trimesh
import trimesh.sample

# you can download the dataset from https://modelnet.cs.princeton.edu/
mesh = trimesh.load_mesh("/path/to/ModelNet10/bed/train/bed_0001.off")
samples, _ = trimesh.sample.sample_surface_even(mesh, 4000)
print(samples.shape[0])
```

This prints numbers around 2730 instead of exactly 4000.
if this is by design then it should be mentioned in the documentation.

btw: does the surface sampling consider the triangle size? that is, will samples cluster on small triangles?

**Comment by mikedh** [comment]
Ah yeah, `sample_surface_even` is a bit odd. It starts with the regular sampling which is robust, quick, and vectorized, it uses area-weighting and should be indifferent to tesselation and not cluster on small triangles. `mesh.sample` will return the exact number of samples requested.

Since the samples are random, `sample_surface_even` then removes samples closer than a certain distance, hence the lower sample count. Yeah I agree the docstring should mention `n <= count` or it should do multiple passes until `n == count`.

**Comment by mikedh** [comment]
I reworked the `remove_close` logic to be a bit faster and reject fewer false positives (https://github.com/mikedh/trimesh/commit/5ed9dc90d27693f4f603efbc369fc2706eb7ef7d), and emit a `log.warning` when the returned sample count is still lower than the requested count. 

Thanks for the report!
