### ISSUE TITLE
How to export Mesh to Step ?

### ISSUE THREAD

**Issue by selvakarna** [mikedh/trimesh#559]
How to export Mesh to Step ?

**Comment by mikedh** [comment]
Hey, so STEP files are a boundary representation format rather than a mesh format, and trimesh doesn't have support for exporting (importing just requires tesselation and is supported). 

Solidworks does let you import a mesh as a solid, and then export as a STEP, but it is a very low quality result, as it is defining an analytical surface for every triangle (i.e. a 30KB STL results in like a 10MB STEP).
