### ISSUE TITLE
Mesh colors changing completely while loading a ply file

### ISSUE THREAD

**Issue by jsaisagar** [mikedh/trimesh#628]
Hi,

I have a mesh which looks like this in meshlab.
![Screenshot from 2019-11-25 09-57-14](https://user-images.githubusercontent.com/6646353/69512725-254de280-0f6b-11ea-99a6-e273768598da.png)

However, when rendereing the image or using scene show(), random colors are being displayed as:
![Screenshot from 2019-11-25 09-56-40](https://user-images.githubusercontent.com/6646353/69512769-53332700-0f6b-11ea-9675-eaa2125e01ff.png)

The ply file is [here](https://drive.google.com/open?id=1ZPWyjeQIZ5ZLNwNEs0RnVm2HhsrfK5ic)

May I know why this is happening?

Thanks,

**Comment by mikedh** [comment]
You mean it isn't supposed to look like that 😁. That mesh has *both* face color and vertex color defined. Usually trimesh tries to detect which of the two is actually defined, and since both are defined it is picking the one with more "signal." 

We could potentially add a `prefer_color=None` for the current automatic selection behavior, or `prefer_color='face'` to use face colors over vertex colors.

Here are the same funhouse colors in meshlab:
![facecolor](https://user-images.githubusercontent.com/1403074/69589263-63192e00-0fa0-11ea-9e3e-fbe6e48b8e56.png)

**Comment by jsaisagar** [comment]
Oh my bad!!
