### ISSUE TITLE
Color face side

### ISSUE THREAD

**Issue by lsabi** [mikedh/trimesh#644]
Hi,

How can I color a certain face of a triangle? Below a screenshot of a model I'm working on.
![face_model](https://user-images.githubusercontent.com/13497689/70129161-87e76280-167e-11ea-9e57-429bc6a257d8.PNG)

The colored side is the wrong side as it will be covered and not visible (it's the bottom), while the other side is completely white and will be the one visible (it's the top).

I'm simply using `mesh.visual.face_colors = [241, 69, 21, 255]`, how can I select the right side?

Thanks.

**Comment by mikedh** [comment]
Hey, usually faces only render from one side (backface culling and whatnot). If you want to see it from the other side, I'd append some faces which had the winding reversed and then set the colors on the reversed faces, something like:

```
In [1]: import trimesh

In [2]: m = trimesh.Trimesh(vertices=[[0,0,0],[1,0,0],[0,1,0]], faces
   ...: =[[0,1,2]])

In [3]: m
Out[3]: <trimesh.Trimesh(vertices.shape=(3, 3), faces.shape=(1, 3))>

In [4]: m.show()
No adjacent faces detected! Did you merge vertices?
Out[4]: SceneViewer(width=1800, height=1350)

In [5]: m.faces
Out[5]: TrackedArray([[0, 2, 1]])

In [7]: import numpy as np

In [8]: m.faces = np.vstack((m.faces, np.fliplr(m.faces)))
```

If you already have faces on both sides, you could check the dot product of face normals against your "side" vector:
```
In [11]: np.dot(m.face_normals, [0,0,1])
Out[11]: array([ 1., -1.])

In [12]: top = np.dot(m.face_normals, [0,0,1]) > 0

In [13]: top
Out[13]: array([ True, False])

In [14]: bottom = ~top

In [15]: bottom
Out[15]: array([False,  True])

```

**Comment by FlorianBertonBrightClue** [comment]
Hi, I have a similar issue. I used a 3d obj from a CAD files, and sometime half of the normals are not in the same direction than the other half.

I tried to use fix_normals(), but it didn't change the rendering.

I also try the solution to add the twice the faces with : m.faces = np.vstack((m.faces, np.fliplr(m.faces)))

But when I'm using this, my mesh became all black.

**Comment by FlorianBertonBrightClue** [comment]
I found the issue:

With a one side mesh, it is necessary to duplicate the table: faces, face_normals and vertices.

If only the faces and face_normals are duplicated, the normals are change when just calling the property _vertex_normals_.

Indeed this property always apply _geometry.weighted_vertex_normals_, which computes a weighted sum of all the normals associated to a vertex. If only the face normals are duplicated in order to flip them, the sum will be equal to 0.

What I did is this:
mesh_1_side # current mesh with one side faces and normals
vertices_2_side = np.vstack((mesh_1_side.vertices.copy(),mesh_1_side.vertices.copy()))
faces_2_sides = np.vstack((mesh_1_side.faces,np.fliplr(mesh_1_side.faces)+mesh_1_side.vertices.shape[0]))
face_normals_2_side = np.vstack((mesh_1_side.face_normals,-1*mesh_1_side.face_normals))
mesh_2_side = trimesh.Trimesh(vertices=vertices_2_side,faces=faces_2_sides,face_normals=face_normals_2_side)

This solution work well in trimesh, but it does not work with Pyrender as I think there is a preprocessing that remove duplicate vertices
