### ISSUE TITLE
load_mesh has inconsistent return type

### ISSUE THREAD

**Issue by staubda** [mikedh/trimesh#661]
I'm using Trimesh to load OBJ files and have noticed that `load_mesh` returns a `Scene` object for multi-material OBJs and a `Trimesh` object for single material OBJs. Is there any reason not to be consistent and always return a `Scene`? Got bitten by this recently.

**Comment by mikedh** [comment]
Yeah, I struggle with this too. In my applications I basically run all my input through `trimesh.scene.split_scene(geometry)` which will always return a `Scene`. I'm pretty open to the change, this would also not be particularly breaking since different inputs can already force people to handle `Scene` objects as you point out. 
 
If anyone has strong opinions, feel free to vote:
👍 OBJ loader will be changed to *always* return `trimesh.Scene`
👎 OBJ loader with single material OBJ continues to sometimes return a `trimesh.Trimesh`

**Comment by drewsherlock** [comment]
👍

**Comment by mikedh** [comment]
Hey, at some point I added the `force` kwarg to `trimesh.load`, which hopefully makes this easier. By default it will return whatever the most sensible thing is for a particular file (`force=None`), but can be forced to either `'mesh'` or `'scene'`:
```
In [1]: import trimesh

In [2]: m = trimesh.load('models/cycloidal.3DXML')

In [3]: m
Out[3]: <trimesh.Scene(len(geometry)=13)>

In [4]: m = trimesh.load('models/cycloidal.3DXML', force='mesh')

In [5]: m
Out[5]: <trimesh.Trimesh(vertices.shape=(219070, 3), faces.shape=(376520, 3))>

In [6]: m = trimesh.load('models/featuretype.STL')

In [7]: m
Out[7]: <trimesh.Trimesh(vertices.shape=(1722, 3), faces.shape=(3476, 3))>

In [8]: m = trimesh.load('models/featuretype.STL', force='scene')

In [9]: m
Out[9]: <trimesh.Scene(len(geometry)=1)>

```
