### ISSUE TITLE
Export FBX file

### ISSUE THREAD

**Issue by lan786** [mikedh/trimesh#738]
Hi @mikedh  thanks for such a terrific tool. I'm using trimesh in my Python project whose output is human actions or poses with joints information and also 3D shape. I can save OBJ file using trimesh for every shape frame but no joints or geometric information. As per my knowledge that FBX file can solve this problem but using trimesh FBX file can't be saved with joints information along with 3D shape or mesh. I read #62 this issue but I'm unable to get it. 
Is there anyway to export FBX file instead of OBJ or STL file using trimesh?

**Comment by mikedh** [comment]
Hey, FBX isn't currently supported and isn't likely to be in the future due to the somewhat proprietary nature of the format (though PR's welcome!). GLTF I believe [supports the concept of skeletons](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#skins), and although trimesh's importer/export doesn't it might be a good place to start
