### ISSUE TITLE
No connected components returned?

### ISSUE THREAD

**Issue by benjiebob** [mikedh/trimesh#76]
Apologies if I'm misunderstanding but I hope you might be able to help me.

Following your demo, I am running mesh.split() on a mesh (see attached horse_simplified.ply in .zip) but keep getting an empty array of dtype=object. This seems to signal that the mesh does not have a single connected component.

Is this a bug or is there a good explanation for this?

Code is simple:

```python
mesh = trimesh.load_mesh('horse_simplified.ply')
components = mesh.split()
# components is: array([], dtype=object)
```

Any help appreciated!

Thanks,

Ben

[meshes.zip](https://github.com/mikedh/trimesh/files/1270738/meshes.zip)

**Comment by mikedh** [comment]
Hey Ben,

I think this is because the (arguably confusing) default behavior for split is to only return watertight components. You can specify `mesh.split(only_watertight=False)` which I think does what you want. Thanks for providing the example mesh! Here's an ipython example:

```
In [1]: import trimesh

In [2]: m = trimesh.load("horse_simplified.ply")

In [3]: m.faces.shape
Out[3]: (2908, 3)

In [4]: m.split?
Signature: m.split(*args, **kwargs)
Docstring:
Returns a list of Trimesh objects, based on face connectivity.
Splits into individual components, sometimes referred to as 'bodies'

Parameters
---------
only_watertight: only meshes which are watertight are returned
adjacency: if not None, override face adjacency with custom values (n,2)

Returns
---------
meshes: (n) list of Trimesh objects
File:      ~/trimesh/trimesh/constants.py
Type:      method

In [5]: m.is_watertight
Out[5]: False

In [6]: split_watertight = m.split()

In [7]: split_all = m.split(only_watertight=False)

In [8]: split_all
Out[8]: 
array([<trimesh.base.Trimesh object at 0x7fdb0ea09ac8>,
       <trimesh.base.Trimesh object at 0x7fdb0ea09fd0>,
       <trimesh.base.Trimesh object at 0x7fdb0ea0b198>], dtype=object)

In [9]: for i in split_all:
   ...:     i.visual.face_colors = trimesh.visual.random_color()
   ...:     

In [10]: trimesh.Scene(split_all).show()
```

**Comment by mikedh** [comment]
Feel free to reopen if you're still seeing this.

**Comment by benjiebob** [comment]
Thanks so much mikedh, this solved my problem :)

**Comment by gbalatz** [comment]
Hello mikehd,

I am having a rather big dataset of connected components.
trimesh.split() returns a list of watertight components. My problem is that i get a lot of "chunks" that are nowhere to find in the original stl. Also is there a way to split components that are connected by faces because of the bad scan i have as a STL file?

**Comment by Marviel** [comment]
@gbalatz would you be able to provide an example mesh demonstrating the problem you're seeing?

**Comment by mikedh** [comment]
Weird! An example mesh would be helpful. You could also try a different graph engine in the split command:


```
# engine:     str, which graph engine to use.                                             
#                  ('networkx', 'scipy', or 'graphtool')                                       
#                  If None, will automatically choose fastest available.  

split = mesh.split(only_watertight=False, engine='networkx')
```

The current automated choice goes graph-tool -> scipy -> networkx (uses the first one which is installed).

**Comment by gbalatz** [comment]
Hello @mikedh  and @Marviel .
Sorry for the late answer as i have been on Holidays.

So the Actual Problem is that i get a dataset and try to split. (Tried the Suggestion of using different engines, didnt work though.) When i split the Mesh, i get an awful lot of obselete Data like this [0] or a mixed up version of the splitted objects i want [1].

Is there any solution do reduce these "chunks" and more importantly to split those connected bars?

Thank you for your Time and Answers.

![chunk](https://user-images.githubusercontent.com/29070528/31936490-04326e8e-b8b2-11e7-8574-f4435622ee63.png)
 
![mixed](https://user-images.githubusercontent.com/29070528/31936508-0bce7084-b8b2-11e7-83d9-be6855014340.png)
