### ISSUE TITLE
[Minor Enhancement] Vertex & Face-specific caching

### ISSUE THREAD

**Issue by Marviel** [mikedh/trimesh#78]
Some elements of the mesh which are cache-invalidated by face-changing operations are only vertex-relevant, and vice-versa.

Take the face adjacency for example -- if a vertex is moved, but there are the same number of faces and vertices, then the face adjacency does not change -- and thus shouldn't need recomputation.

It would be cool if there was a mechanism which cached each @util.cache_decorator property by the specific arrays which had changed.

**Comment by mikedh** [comment]
Yeah that would be neat. It would probably need to work like each cached value is associated with a specific key in the DataStore, and if none is specified it is associated with all the keys (any changes dump the cache). 

Also Primitives keep different keys in the DataStore so that would probably need to be handled as well (AKA in a primitive faces are in the cache, and things like 'extents' are in the DataStore).

**Comment by mikedh** [comment]
I actually played around with this a while back and it was a bag of worms. Happy to accept PR's on this if you can think up a nice way of doing it, or I may also take another stab at some point but no promises. Closing for now, though good idea and thanks for the report!
