### ISSUE TITLE
failed to load image 

### ISSUE THREAD

**Issue by ucalyptus** [mikedh/trimesh#956]
# Motive
- Trying to load a chair mesh obj file I downloaded from cgtrader.com . 
- Goal is to load it , and sample a point cloud (2000 points say) , from this mesh.

# [Gist Colab to reproduce this issue](https://colab.research.google.com/gist/ucalyptus/de9b0d7199b5d4ea59813f6ddded9a52/sample-a-point-cloud-from-a-chair-s-mesh.ipynb)

Thanks for maintaing this framework @mikedh

**Comment by mikedh** [comment]
Hey, it looked like your example worked? It output a bunch of warnings because it wasn't able to load a bunch of referenced images because they weren't included (and probably because you don't have PIL), but your
`print(type(mesh))` output `<class 'trimesh.base.Trimesh'>` which is correct, and the points probably sampled correctly.

**Comment by ucalyptus** [comment]
Oh. Thanks then
