### ISSUE TITLE
Mesh and curvy slices

### ISSUE THREAD

**Issue by gbalatz** [mikedh/trimesh#96]
Hello Mike,

Is there a way to define curvy slices? As i looked through the library, i only found the possibility to slice in the direction of an axis.

My point is to slice a Mesh in multiple slices with a predefined degree or radius of curve.

Greetings

**Comment by mikedh** [comment]
Hey, that's a bit of an uncommon thing to do so it probably wouldn't make sense to be in trimesh itself. That being said a quick way to do it could be to take a cylinder and your mesh, do a boolean operation (I recommend the SCAD backend), and then find the faces that weren't in either source mesh.

It's a little weird in general because at the slice you really have all circular arcs rather than line segments. 

You could also do it the proper way by defining two arbitrary axis, perpendicular to each other and to the cylinder axis, and the compute the dot product of each vertex, then combine the two dot products into a radius. Then basically re- implement the intersections code with the 'signs' variable meaning under/over the cylinder radius rather than on one side or the other of a plane.
